import React,{FormEvent,useEffect,useState} from 'react';
import toast from 'react-hot-toast';
import {api} from '../api/client';
import {ShieldCheck,Save} from 'lucide-react';

const empty={first_name:'',last_name:'',birth_date:'',gender:'',nationality:'Togo',document_type:'Non renseigné',document_number:'0000',blood_type:'NC',height:'',weight:'',allergies:'',conditions:'',medications:'',surgeries:'',disabilities:'',doctor_name:'',doctor_phone:'',contact_name:'',contact_phone:'',contact_relation:'Proche'};

export function Profile(){
  const [form,setForm]=useState<any>(empty);const[contacts,setContacts]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [pin,setPin]=useState('');const [confirmation,setConfirmation]=useState('');const [pinConfigured,setPinConfigured]=useState(false);const[deletePassword,setDeletePassword]=useState('');const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[passwordConfirmation,setPasswordConfirmation]=useState('');
  useEffect(()=>{api.get('/profil/me').then(({data})=>{const p=data.profile||{};setForm({...empty,...p,height:p.height??'',weight:p.weight??''});setContacts(data.emergency_contacts||[]);setPinConfigured(Boolean(p.pin_configured));}).catch(()=>toast.error('Impossible de charger votre fiche.')).finally(()=>setLoading(false));},[]);
  const field=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:event.target.value});
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await api.post('/profil',{profile_type:form.profile_type||'adult',first_name:form.first_name,last_name:form.last_name,birth_date:form.birth_date,gender:form.gender,nationality:form.nationality,document_type:form.document_type,document_number:form.document_number,blood_type:form.blood_type,height:form.height?Number(form.height):null,weight:form.weight?Number(form.weight):null,allergies:form.allergies,conditions:form.conditions,medications:form.medications,surgeries:form.surgeries,disabilities:form.disabilities,doctor_name:form.doctor_name,doctor_phone:form.doctor_phone,has_vehicle:Boolean(form.has_vehicle),vehicle_type:form.vehicle_type||'',plate:form.plate||'',brand:form.brand||'',model:form.model||'',emergency_contacts:contacts.filter(c=>c.name&&c.phone).map(c=>({name:c.name,phone:c.phone,relation:c.relation||'Proche'}))});toast.success('Fiche médicale enregistrée.');}catch(e:any){toast.error(e?.response?.data?.detail||'Enregistrement impossible.');}finally{setSaving(false);}};
  const updatePin=async()=>{if(!/^\d{4,6}$/.test(pin))return toast.error('Le PIN doit contenir 4 à 6 chiffres.');if(pin!==confirmation)return toast.error('La confirmation ne correspond pas.');try{await api.put('/profil/pin',{pin});setPin('');setConfirmation('');setPinConfigured(true);toast.success('PIN personnel renouvelé.');}catch(e:any){toast.error(e?.response?.data?.detail||'Modification impossible.');}};
  const clearMedicalData=async()=>{if(!deletePassword)return toast.error('Saisissez votre mot de passe.');if(!window.confirm('Effacer définitivement les données médicales, contacts et PIN ?'))return;try{await api.delete('/profil/medical-data',{data:{password:deletePassword}});setDeletePassword('');setPinConfigured(false);toast.success('Données médicales effacées.');location.reload();}catch(e:any){toast.error(e?.response?.data?.detail||'Suppression impossible.');}};
  const updatePassword=async()=>{if(newPassword!==passwordConfirmation)return toast.error('La confirmation ne correspond pas.');try{await api.put('/auth/password',{current_password:currentPassword,new_password:newPassword});setCurrentPassword('');setNewPassword('');setPasswordConfirmation('');toast.success('Mot de passe modifié.');}catch(e:any){toast.error(e?.response?.data?.detail||'Modification impossible.');}};
  if(loading)return <div className="page-body"><div className="lotisec-card">Chargement de votre fiche…</div></div>;
  const input=(label:string,key:string,type='text')=><div><label>{label}</label><input type={type} value={form[key]??''} onChange={field(key)} /></div>;
  return <div className="page-body" style={{paddingBottom:'7rem'}}><header className="page-header"><div><div className="eyebrow">Fiche de secours</div><h1>Mon profil médical</h1><p>Ces données restent privées et ne sont révélées qu’après une autorisation valide.</p></div><ShieldCheck size={36}/></header>
    <form onSubmit={save} className="lotisec-card" style={{display:'grid',gap:'1rem',marginBottom:'1rem'}}><h2>Identité et données vitales</h2><div className="profile-form-grid">{input('Prénom','first_name')}{input('Nom','last_name')}{input('Date de naissance','birth_date')}{input('Sexe','gender')}{input('Nationalité','nationality')}{input('Groupe sanguin','blood_type')}{input('Taille (cm)','height','number')}{input('Poids (kg)','weight','number')}{input('Allergies','allergies')}{input('Maladies chroniques','conditions')}{input('Traitements','medications')}{input('Handicap / besoins spécifiques','disabilities')}{input('Médecin traitant','doctor_name')}{input('Téléphone du médecin','doctor_phone')}</div><h2>Contacts d'urgence</h2>{contacts.map((contact,index)=><div className="profile-form-grid" key={index}><div><label>Nom</label><input value={contact.name||''} onChange={e=>setContacts(contacts.map((c,i)=>i===index?{...c,name:e.target.value}:c))}/></div><div><label>Téléphone</label><input value={contact.phone||''} onChange={e=>setContacts(contacts.map((c,i)=>i===index?{...c,phone:e.target.value}:c))}/></div><div><label>Relation</label><input value={contact.relation||''} onChange={e=>setContacts(contacts.map((c,i)=>i===index?{...c,relation:e.target.value}:c))}/></div><button type="button" className="btn ghost" onClick={()=>setContacts(contacts.filter((_,i)=>i!==index))}>Retirer</button></div>)}<button type="button" className="btn ghost" onClick={()=>setContacts([...contacts,{name:'',phone:'',relation:'Proche'}])}>Ajouter un contact</button><button className="btn primary" disabled={saving}><Save size={18}/>{saving?'Enregistrement…':'Enregistrer ma fiche'}</button></form>
    <section className="lotisec-card" style={{display:'grid',gap:'1rem',marginBottom:'1rem'}}><h2>PIN personnel de secours</h2><p className="text-secondary">{pinConfigured?'Un PIN est configuré. Vous pouvez le renouveler ici.':'Définissez votre PIN avant de partager votre QR.'} Il n’est jamais inclus dans le QR.</p><div className="profile-form-grid"><div><label>Nouveau PIN</label><input type="password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))}/></div><div><label>Confirmer le PIN</label><input type="password" inputMode="numeric" maxLength={6} value={confirmation} onChange={e=>setConfirmation(e.target.value.replace(/\D/g,'').slice(0,6))}/></div></div><button type="button" className="btn ghost" onClick={updatePin}>Définir ou renouveler le PIN</button></section><section className="lotisec-card" style={{display:'grid',gap:'1rem',marginBottom:'1rem'}}><h2>Mot de passe du compte</h2><div className="profile-form-grid"><div><label>Mot de passe actuel</label><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></div><div><label>Nouveau mot de passe</label><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></div><div><label>Confirmer</label><input type="password" value={passwordConfirmation} onChange={e=>setPasswordConfirmation(e.target.value)}/></div></div><button type="button" className="btn ghost" onClick={updatePassword}>Modifier le mot de passe</button></section><section className="lotisec-card" style={{display:'grid',gap:'1rem',borderColor:'var(--color-danger)'}}><h2>Effacer ma fiche médicale</h2><p className="text-secondary">Supprime les constantes médicales, contacts d’urgence, véhicule et PIN. Le compte et le QR restent actifs avec une fiche vide.</p><div><label>Confirmer avec le mot de passe du compte</label><input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/></div><button type="button" className="btn danger" onClick={clearMedicalData}>Effacer mes données médicales</button></section>
  </div>;
}
