import React,{FormEvent,useEffect,useState} from 'react';
import toast from 'react-hot-toast';
import {api} from '../api/client';
import {ShieldCheck,Save} from 'lucide-react';

const empty={first_name:'',last_name:'',birth_date:'',gender:'',nationality:'Togo',document_type:'Non renseigné',document_number:'0000',blood_type:'NC',height:'',weight:'',allergies:'',conditions:'',medications:'',surgeries:'',disabilities:'',doctor_name:'',doctor_phone:'',contact_name:'',contact_phone:'',contact_relation:'Proche'};

export function Profile(){
  const [form,setForm]=useState<any>(empty);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [pin,setPin]=useState('');const [confirmation,setConfirmation]=useState('');const [pinConfigured,setPinConfigured]=useState(false);
  useEffect(()=>{api.get('/profil/me').then(({data})=>{const p=data.profile||{},c=data.emergency_contacts?.[0]||{};setForm({...empty,...p,height:p.height??'',weight:p.weight??'',contact_name:c.name||'',contact_phone:c.phone||'',contact_relation:c.relation||'Proche'});setPinConfigured(Boolean(p.pin_configured));}).catch(()=>toast.error('Impossible de charger votre fiche.')).finally(()=>setLoading(false));},[]);
  const field=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:event.target.value});
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await api.post('/profil',{profile_type:form.profile_type||'adult',first_name:form.first_name,last_name:form.last_name,birth_date:form.birth_date,gender:form.gender,nationality:form.nationality,document_type:form.document_type,document_number:form.document_number,blood_type:form.blood_type,height:form.height?Number(form.height):null,weight:form.weight?Number(form.weight):null,allergies:form.allergies,conditions:form.conditions,medications:form.medications,surgeries:form.surgeries,disabilities:form.disabilities,doctor_name:form.doctor_name,doctor_phone:form.doctor_phone,has_vehicle:Boolean(form.has_vehicle),vehicle_type:form.vehicle_type||'',plate:form.plate||'',brand:form.brand||'',model:form.model||'',emergency_contacts:form.contact_name&&form.contact_phone?[{name:form.contact_name,phone:form.contact_phone,relation:form.contact_relation||'Proche'}]:[]});toast.success('Fiche médicale enregistrée.');}catch(e:any){toast.error(e?.response?.data?.detail||'Enregistrement impossible.');}finally{setSaving(false);}};
  const updatePin=async()=>{if(!/^\d{4,6}$/.test(pin))return toast.error('Le PIN doit contenir 4 à 6 chiffres.');if(pin!==confirmation)return toast.error('La confirmation ne correspond pas.');try{await api.put('/profil/pin',{pin});setPin('');setConfirmation('');setPinConfigured(true);toast.success('PIN personnel renouvelé.');}catch(e:any){toast.error(e?.response?.data?.detail||'Modification impossible.');}};
  if(loading)return <div className="page-body"><div className="lotisec-card">Chargement de votre fiche…</div></div>;
  const input=(label:string,key:string,type='text')=><div><label>{label}</label><input type={type} value={form[key]??''} onChange={field(key)} /></div>;
  return <div className="page-body" style={{paddingBottom:'7rem'}}><header className="page-header"><div><div className="eyebrow">Fiche de secours</div><h1>Mon profil médical</h1><p>Ces données restent privées et ne sont révélées qu’après une autorisation valide.</p></div><ShieldCheck size={36}/></header>
    <form onSubmit={save} className="lotisec-card" style={{display:'grid',gap:'1rem',marginBottom:'1rem'}}><h2>Identité et données vitales</h2><div className="profile-form-grid">{input('Prénom','first_name')}{input('Nom','last_name')}{input('Date de naissance','birth_date')}{input('Sexe','gender')}{input('Nationalité','nationality')}{input('Groupe sanguin','blood_type')}{input('Taille (cm)','height','number')}{input('Poids (kg)','weight','number')}{input('Allergies','allergies')}{input('Maladies chroniques','conditions')}{input('Traitements','medications')}{input('Handicap / besoins spécifiques','disabilities')}{input('Médecin traitant','doctor_name')}{input('Téléphone du médecin','doctor_phone')}{input("Contact d'urgence",'contact_name')}{input('Téléphone du contact','contact_phone')}{input('Lien avec le contact','contact_relation')}</div><button className="btn primary" disabled={saving}><Save size={18}/>{saving?'Enregistrement…':'Enregistrer ma fiche'}</button></form>
    <section className="lotisec-card" style={{display:'grid',gap:'1rem'}}><h2>PIN personnel de secours</h2><p className="text-secondary">{pinConfigured?'Un PIN est configuré. Vous pouvez le renouveler ici.':'Définissez votre PIN avant de partager votre QR.'} Il n’est jamais inclus dans le QR.</p><div className="profile-form-grid"><div><label>Nouveau PIN</label><input type="password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))}/></div><div><label>Confirmer le PIN</label><input type="password" inputMode="numeric" maxLength={6} value={confirmation} onChange={e=>setConfirmation(e.target.value.replace(/\D/g,'').slice(0,6))}/></div></div><button type="button" className="btn ghost" onClick={updatePin}>Définir ou renouveler le PIN</button></section>
  </div>;
}
