import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {MapContainer,Marker,Polyline,TileLayer} from 'react-leaflet';
import {ArrowLeft,CheckCircle,MessageCircle,Send} from 'lucide-react';
import toast from 'react-hot-toast';
import {api} from '../api/client';import {supabase} from '../api/supabase';
const labels:Record<string,string>={searching:'Recherche en cours',offered:'Proposition envoyée',accepted:'Zem affecté',driver_en_route:'Le Zem arrive',driver_arrived:'Zem arrivé',ready_to_start:'Prêt à partir',in_progress:'Trajet en cours',driver_completed:'Arrivée à confirmer',completed:'Terminé',canceled:'Annulé',expired:'Expiré',no_show:'Absence signalée',disputed:'Contesté'};
export function RideDetail(){const {rideId}=useParams();const navigate=useNavigate();const user=useMemo(()=>JSON.parse(localStorage.getItem('lotisec_user')||'{}'),[]);const [ride,setRide]=useState<any>();const [position,setPosition]=useState<any>();const [messages,setMessages]=useState<any[]>([]);const [body,setBody]=useState('');
  const load=async()=>{if(!rideId)return;try{const [{data:r},{data:p},{data:m}]=await Promise.all([api.get(`/zem/rides/${rideId}`),api.get(`/zem/rides/${rideId}/positions/latest`),api.get(`/zem/rides/${rideId}/messages`)]);setRide(r.ride);setPosition(p.position);setMessages(m.messages||[]);await api.patch(`/zem/rides/${rideId}/messages/read`,{});}catch{toast.error('Course inaccessible.');}};
  useEffect(()=>{load();const timer=setInterval(load,15000);if(!supabase)return()=>clearInterval(timer);const channel=supabase.channel(`web-ride-${rideId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rides',filter:`id=eq.${rideId}`},({new:r})=>setRide(r)).on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_positions',filter:`ride_id=eq.${rideId}`},({new:p})=>setPosition(p)).on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_messages',filter:`ride_id=eq.${rideId}`},({new:m})=>setMessages(previous=>previous.some(item=>item.id===m.id)?previous:[...previous,m])).subscribe();return()=>{clearInterval(timer);supabase?.removeChannel(channel);};},[rideId]);
  if(!ride)return <div className="app-content"><div className="spinner"/></div>;const driver=user.id===ride.zem_id;const approaching=['accepted','driver_en_route','driver_arrived','ready_to_start'].includes(ride.status);const points=approaching&&position?[[position.latitude,position.longitude],[ride.origin_lat,ride.origin_lng]]:[[ride.origin_lat,ride.origin_lng],[ride.dest_lat,ride.dest_lng]];const actions:any[]=[];if(driver&&ride.status==='accepted')actions.push(["Commencer l'approche",'driver_en_route']);if(driver&&ride.status==='driver_en_route')actions.push(['Je suis arrivé','driver_arrived']);if(!driver&&ride.status==='driver_arrived')actions.push(['Je suis prêt','passenger_ready']);if(driver&&ride.status==='ready_to_start')actions.push(['Démarrer','start']);if(driver&&ride.status==='in_progress')actions.push(['Arrivé à destination','driver_completed']);if(!driver&&ride.status==='driver_completed')actions.push(['Confirmer la fin','confirm_complete']);const chatOpen=['accepted','driver_en_route','driver_arrived','ready_to_start','in_progress','driver_completed'].includes(ride.status);
  const act=async(action:string)=>{try{const {data}=await api.post(`/zem/rides/${ride.id}/action`,{action});setRide(data.ride);}catch(e:any){toast.error(e.response?.data?.detail||'Action impossible.');}};const send=async(e:FormEvent)=>{e.preventDefault();const text=body.trim();if(!text)return;setBody('');try{const {data}=await api.post(`/zem/rides/${ride.id}/messages`,{body:text,client_message_id:crypto.randomUUID()});setMessages(previous=>previous.some(m=>m.id===data.message.id)?previous:[...previous,data.message]);}catch{setBody(text);toast.error('Message non envoyé.');}};
  return <div className="app-content" style={{padding:'1rem',maxWidth:900,margin:'0 auto'}}><button className="btn ghost" onClick={()=>navigate('/trajets')}><ArrowLeft size={18}/> Retour</button><div className="lotisec-card"><h2>{labels[ride.status]||ride.status}</h2><p>{ride.distance_km} km · {ride.price_fcfa} FCFA</p><div style={{height:320}}><MapContainer center={approaching?[ride.origin_lat,ride.origin_lng]:[ride.dest_lat,ride.dest_lng]} zoom={14} style={{height:'100%'}}><TileLayer url="https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"/><Marker position={[ride.origin_lat,ride.origin_lng]}/><Marker position={[ride.dest_lat,ride.dest_lng]}/>{position&&<Marker position={[position.latitude,position.longitude]}/>}<Polyline positions={points as any} color="#1565D8"/></MapContainer></div>{actions.map(([label,action])=><button key={action} className="btn primary mt-4" onClick={()=>act(action)}><CheckCircle size={18}/>{label}</button>)}</div><div className="lotisec-card"><h3><MessageCircle size={19}/> Discussion</h3><div style={{maxHeight:300,overflowY:'auto',display:'flex',flexDirection:'column',gap:8}}>{messages.map(message=><div key={message.id} style={{alignSelf:message.sender_id===user.id?'flex-end':'flex-start',background:message.sender_id===user.id?'var(--color-primary)':'#eef2f2',color:message.sender_id===user.id?'white':'inherit',padding:'0.65rem 0.8rem',borderRadius:14,maxWidth:'80%'}}>{message.body}</div>)}</div>{chatOpen?<form onSubmit={send} style={{display:'flex',gap:8,marginTop:12}}><input value={body} onChange={event=>setBody(event.target.value)} placeholder="Écrire un message" maxLength={1000}/><button className="btn primary" aria-label="Envoyer"><Send size={18}/></button></form>:<p className="text-secondary">Conversation en lecture seule.</p>}</div></div>;
}
