import { useState } from 'react'
import { Activity, ArrowRightLeft, BedDouble, BellRing, Building2, CheckCircle2, Download, HeartPulse, Hospital, Network, Radio, Save, ShieldCheck, Stethoscope, UserRoundCheck } from 'lucide-react'
import { Kpi, PageTitle, Status } from '../components/UI'
import { downloadXlsx } from '../lib/xlsx'
import { getPortalGatewayConfig, HEALTH_EVENTS } from '../services/portalGateway'

const portalConfig=getPortalGatewayConfig()

const incomingSeed=[
  {id:'TRF-26091',victim:'Victime #081-A',severity:'Critique',origin:'Carrefour GTA',ambulance:'AMB-07',eta:6,need:'Traumatologie',status:'À confirmer'},
  {id:'TRF-26090',victim:'Victime #080-A',severity:'Élevée',origin:'Tokoin-Solidarité',ambulance:'AMB-03',eta:11,need:'Imagerie',status:'Préparation en cours'},
  {id:'TRF-26089',victim:'Victime #079-A',severity:'Modérée',origin:'Bè-Klikamé',ambulance:'AMB-12',eta:18,need:'Urgences',status:'Acceptée'},
]

const healthHistory=[
  {id:'DOS-26088',victim:'Victime #078-A',admission:'00:42',service:'Traumatologie',delay:'4 min',outcome:'Prise en charge'},
  {id:'DOS-26087',victim:'Victime #077-A',admission:'23:18',service:'Urgences',delay:'7 min',outcome:'Observation'},
  {id:'DOS-26086',victim:'Victime #076-A',admission:'22:51',service:'Chirurgie',delay:'5 min',outcome:'Hospitalisation'},
  {id:'DOS-26085',victim:'Victime #075-A',admission:'21:36',service:'Imagerie',delay:'9 min',outcome:'Réorientation'},
]

export default function HealthPortal({view='health-dashboard',hospitals=[],alerts=[],mission,auditLog=[],mobileFeedStatus,onUpdateHospital,onPublishEvent,onNotify}){
  const [incoming,setIncoming]=useState(incomingSeed)
  const [selectedFacilityId,setSelectedFacilityId]=useState(hospitals[0]?.id)
  const facility=hospitals.find(item=>item.id===selectedFacilityId)||hospitals[0]
  const totalBeds=hospitals.reduce((sum,item)=>sum+(Number(item.beds)||0),0)
  const averageOccupancy=hospitals.length?Math.round(hospitals.reduce((sum,item)=>sum+(Number(item.occupancy)||0),0)/hospitals.length):0

  const updateTransfer=(id,status)=>{
    setIncoming(items=>items.map(item=>item.id===id?{...item,status}:item))
    onPublishEvent?.(HEALTH_EVENTS.admissionDecision,{transferId:id,status,facilityId:selectedFacilityId,decidedAt:new Date().toISOString()})
    onNotify?.(`${id} : ${status}`,'green')
  }
  const updateBeds=delta=>{
    if(!facility) return
    const beds=Math.max(0,Number(facility.beds||0)+delta)
    onUpdateHospital?.(facility.id,{beds})
  }
  const exportHealthReport=()=>{
    downloadXlsx(`rapport-sante-lotisec-${new Date().toISOString().slice(0,10)}.xlsx`,[
      {name:'Synthèse santé',rows:[['INDICATEUR','VALEUR'],['Hôpitaux connectés',hospitals.length],['Places disponibles',totalBeds],['Occupation moyenne',`${averageOccupancy}%`],['Transferts entrants',incoming.length],['Dossiers anonymisés',healthHistory.length]],headerRows:[0]},
      {name:'Capacités',rows:[['ID','Hôpital','Spécialité','Places disponibles','Occupation (%)','Réception','Actualisation'],...hospitals.map(item=>[item.id,item.name,item.specialty,item.beds,item.occupancy,item.reception,item.lastCapacityUpdate])],headerRows:[0],autoFilter:1},
      {name:'Transferts',rows:[['ID transfert','Référence victime','Gravité','Origine','Ambulance','ETA (min)','Besoin','Statut'],...incoming.map(item=>[item.id,item.victim,item.severity,item.origin,item.ambulance,item.eta,item.need,item.status])],headerRows:[0],autoFilter:1},
      {name:'Admissions anonymisées',rows:[['Dossier','Référence victime','Admission','Service','Délai','Issue'],...healthHistory.map(item=>[item.id,item.victim,item.admission,item.service,item.delay,item.outcome])],headerRows:[0],autoFilter:1},
    ])
    onNotify?.('Rapport santé XLSX téléchargé','green')
  }

  const common={hospitals,alerts,mission,auditLog,mobileFeedStatus,incoming,facility,selectedFacilityId,setSelectedFacilityId,totalBeds,averageOccupancy,updateTransfer,updateBeds,exportHealthReport,onNotify}
  if(view==='health-admissions') return <Admissions {...common}/>
  if(view==='health-capacity') return <Capacity {...common}/>
  if(view==='health-transfers') return <Transfers {...common}/>
  if(view==='health-records') return <Records {...common}/>
  if(view==='health-network') return <HealthNetwork {...common}/>
  if(view==='health-settings') return <HealthSettings {...common}/>
  return <HealthDashboard {...common}/>
}

function HealthDashboard({hospitals,totalBeds,averageOccupancy,incoming,mobileFeedStatus,updateTransfer}){
  const awaiting=incoming.filter(item=>item.status==='À confirmer').length
  return <>
    <PageTitle title="Tableau de bord hospitalier" subtitle="Préparer l’accueil des victimes et coordonner les capacités avec le centre opérationnel." action={<Status tone={mobileFeedStatus==='connected'?'green':'blue'}><Radio size={13}/>{mobileFeedStatus==='connected'?'TEMPS RÉEL CONNECTÉ':'MODE TEST SANTÉ'}</Status>}/>
    <section className="surface mb-4 overflow-hidden border-emerald-200 dark:border-emerald-900"><div className="bg-gradient-to-r from-emerald-700 to-teal-500 p-5 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><Stethoscope size={23}/></span><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-100">Permanence hospitalière</div><h3 className="mt-1 text-xl font-bold">CHU Tokoin · Urgences actives</h3><p className="mt-1 text-xs text-emerald-50">Équipe de garde : 2 médecins · 4 infirmiers · 1 traumatologue</p></div></div><div className="rounded-2xl bg-white/15 px-4 py-3 text-center"><b className="block text-2xl">{awaiting}</b><span className="text-xs text-emerald-50">confirmation(s) attendue(s)</span></div></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Transferts entrants" value={incoming.length} icon={ArrowRightLeft} tone="blue" hint="mis à jour par le centre opérationnel"/><Kpi label="Places disponibles" value={totalBeds} icon={BedDouble} tone="green" hint={`${hospitals.length} hôpital(aux) connecté(s)`}/><Kpi label="Occupation moyenne" value={`${averageOccupancy}%`} icon={Activity} tone="violet" hint="réseau hospitalier LOTISEC"/><Kpi label="Accueil à confirmer" value={awaiting} icon={BellRing} tone="red" hint="validation humaine requise"/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Arrivées annoncées</h3><p className="mt-1 text-xs muted">Les identités des victimes sont anonymisées.</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{incoming.map(item=><div key={item.id} className="p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div className="flex items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.severity==='Critique'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}><HeartPulse size={18}/></span><div><div className="flex flex-wrap items-center gap-2"><b>{item.victim}</b><Status tone={item.severity==='Critique'?'red':'amber'}>{item.severity}</Status></div><p className="mt-1 text-xs muted">{item.origin} · {item.ambulance} · besoin : {item.need}</p></div></div><div className="flex items-center gap-2"><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold dark:bg-slate-800">ETA {item.eta} min</span>{item.status==='À confirmer'?<button type="button" onClick={()=>updateTransfer(item.id,'Acceptée')} className="btn-primary !bg-emerald-600">Accepter</button>:<Status tone="green">{item.status}</Status>}</div></div></div>)}</div></section><section className="surface p-4"><h3 className="font-semibold">Capacités du réseau</h3><div className="mt-4 space-y-4">{hospitals.map(item=><div key={item.id}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="truncate font-semibold">{item.name}</span><b>{item.beds} places</b></div><div className="h-2.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-2.5 rounded-full ${item.occupancy>84?'bg-red-500':item.occupancy>70?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${item.occupancy}%`}}/></div><div className="mt-1 text-[10px] muted">Occupation {item.occupancy}% · {item.reception}</div></div>)}</div></section></div>
  </>
}

function Admissions({incoming,updateTransfer}){
  return <><PageTitle title="Réceptions d’urgence" subtitle="Valider l’accueil, préparer le box et informer automatiquement l’équipe terrain." action={<Status tone="red">{incoming.filter(item=>item.status==='À confirmer').length} À CONFIRMER</Status>}/><section className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="bg-emerald-50 text-xs text-emerald-800 dark:bg-emerald-950/25 dark:text-emerald-200"><tr><th className="p-3">Transfert</th><th>Victime</th><th>Gravité</th><th>Provenance</th><th>Ressource</th><th>ETA</th><th>Besoin clinique</th><th>Décision</th></tr></thead><tbody>{incoming.map(item=><tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{item.id}</td><td>{item.victim}</td><td><Status tone={item.severity==='Critique'?'red':'amber'}>{item.severity}</Status></td><td>{item.origin}</td><td>{item.ambulance}</td><td><b>{item.eta} min</b></td><td>{item.need}</td><td><div className="flex gap-2">{item.status==='À confirmer'?<><button type="button" onClick={()=>updateTransfer(item.id,'Acceptée')} className="btn-primary !bg-emerald-600 !px-3 !py-1.5">Accepter</button><button type="button" onClick={()=>updateTransfer(item.id,'Réorientation demandée')} className="btn-secondary !px-3 !py-1.5">Réorienter</button></>:<button type="button" onClick={()=>updateTransfer(item.id,'Box prêt')} className="btn-secondary !px-3 !py-1.5">{item.status}</button>}</div></td></tr>)}</tbody></table></div></section><section className="surface mt-4 border-blue-200 bg-blue-50/50 p-4 dark:border-blue-900 dark:bg-blue-950/20"><div className="flex gap-3"><ShieldCheck size={20} className="shrink-0 text-blue-600"/><div><b className="text-sm">Validation attribuée et traçable</b><p className="mt-1 text-xs leading-5 muted">Chaque acceptation ou demande de réorientation est horodatée et retournée au centre opérationnel via l’événement <code>hospital:admission:decision</code>.</p></div></div></section></>
}

function Capacity({hospitals,facility,selectedFacilityId,setSelectedFacilityId,updateBeds,onNotify}){
  const [saving,setSaving]=useState(false)
  const save=()=>{setSaving(true);setTimeout(()=>{setSaving(false);onNotify?.('Capacité hospitalière synchronisée avec LOTISEC','green')},700)}
  return <><PageTitle title="Capacités d’accueil" subtitle="Mettre à jour les places, le niveau d’occupation et les services disponibles." action={<button type="button" onClick={save} disabled={saving} className="btn-primary !bg-emerald-600"><Save size={16}/>{saving?'Synchronisation…':'Publier les capacités'}</button>}/><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><section className="surface p-4"><h3 className="font-semibold">Hôpital sélectionné</h3><div className="mt-3 space-y-2">{hospitals.map(item=><button type="button" key={item.id} onClick={()=>setSelectedFacilityId(item.id)} className={`w-full rounded-xl border p-3 text-left transition ${selectedFacilityId===item.id?'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/25':'border-slate-200 dark:border-slate-700'}`}><div className="flex justify-between gap-2"><b className="text-sm">{item.name}</b><Status tone={item.reception==='Ouverte'?'green':'amber'}>{item.reception}</Status></div><p className="mt-1 text-xs muted">{item.specialty} · actualisé {item.lastCapacityUpdate}</p></button>)}</div></section><section className="surface p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-600">Déclaration en cours</div><h3 className="mt-1 text-xl font-bold">{facility?.name}</h3></div><Status tone="green"><Radio size={13}/>CANAL ACTIF</Status></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-center dark:border-emerald-900 dark:bg-emerald-950/20"><span className="text-xs text-emerald-700 dark:text-emerald-300">Places immédiatement disponibles</span><div className="mt-3 flex items-center justify-center gap-4"><button type="button" onClick={()=>updateBeds(-1)} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-xl font-bold shadow-sm dark:bg-slate-900">−</button><b className="min-w-14 text-4xl text-emerald-700 dark:text-emerald-300">{facility?.beds||0}</b><button type="button" onClick={()=>updateBeds(1)} className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-600 text-xl font-bold text-white">+</button></div></div><div className="rounded-2xl border border-slate-200 p-5 dark:border-slate-700"><span className="text-xs muted">Occupation déclarée</span><b className="mt-3 block text-4xl">{facility?.occupancy||0}%</b><div className="mt-3 h-2.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2.5 rounded-full bg-amber-500" style={{width:`${facility?.occupancy||0}%`}}/></div></div></div><div className="mt-5"><div className="text-xs font-semibold">Services disponibles</div><div className="mt-2 flex flex-wrap gap-2">{(facility?.services||[]).map(service=><span key={service} className="chip bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"><CheckCircle2 size={13}/>{service}</span>)}</div></div></section></div></>
}

function Transfers({incoming,mission,updateTransfer}){
  return <><PageTitle title="Transferts entrants" subtitle="Suivre l’ambulance, l’ETA et les préparatifs jusqu’à la remise au service hospitalier."/><div className="grid gap-4 lg:grid-cols-3">{incoming.map((item,index)=>{const progress=Math.max(12,Math.min(92,78-index*23));return <article key={item.id} className={`surface overflow-hidden ${item.status==='Acceptée'?'border-emerald-300 dark:border-emerald-900':''}`}><div className={`p-4 text-white ${item.status==='Acceptée'?'bg-emerald-600':'bg-slate-800'}`}><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-wider">{item.id}</span><span className="rounded-full bg-white/15 px-2 py-1 text-[9px] font-bold">{item.status}</span></div><h3 className="mt-2 font-bold">{item.victim}</h3><p className="mt-1 text-xs opacity-80">{item.ambulance} · depuis {item.origin}</p></div><div className="p-4"><div className="grid grid-cols-3 gap-2 text-center text-xs"><Small label="ETA" value={`${item.eta} min`}/><Small label="Besoin" value={item.need}/><Small label="Gravité" value={item.severity}/></div><div className="mt-4"><div className="mb-1 flex justify-between text-[10px] muted"><span>Progression vers l’hôpital</span><b>{progress}%</b></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded-full bg-gradient-to-r from-blue-500 to-emerald-500" style={{width:`${progress}%`}}/></div></div><button type="button" onClick={()=>updateTransfer(item.id,'Box prêt')} className="btn-secondary mt-4 w-full"><UserRoundCheck size={16}/>Signaler le box prêt</button></div></article>})}</div>{mission&&<section className="surface mt-4 p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-100 text-blue-700"><ArrowRightLeft size={19}/></span><div><b className="text-sm">Mission LOTISEC active : {mission.id}</b><p className="mt-1 text-xs muted">{mission.ambulanceId} · statut {mission.status} · destination {mission.hospitalId||mission.recommendedHospitalId||'en validation'}</p></div></div></section>}</>
}

function Records({exportHealthReport}){
  return <><PageTitle title="Historique anonymisé" subtitle="Dossiers de prise en charge sans nom, téléphone ni pièce d’identité de victime." action={<button type="button" onClick={exportHealthReport} className="btn-primary !bg-emerald-600"><Download size={16}/>Exporter XLSX</button>}/><section className="surface overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Dossier</th><th>Victime anonymisée</th><th>Admission</th><th>Service</th><th>Délai d’accueil</th><th>Issue</th></tr></thead><tbody>{healthHistory.map(item=><tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{item.id}</td><td>{item.victim}</td><td>{item.admission}</td><td>{item.service}</td><td>{item.delay}</td><td><Status tone="green">{item.outcome}</Status></td></tr>)}</tbody></table></div></section></>
}

function HealthNetwork({hospitals,totalBeds,averageOccupancy}){
  return <><PageTitle title="Réseau hospitalier LOTISEC" subtitle="Disponibilité consolidée des hôpitaux et centres de santé partenaires."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Hôpitaux connectés" value={hospitals.length} icon={Building2} tone="green" hint="synchronisation temps réel"/><Kpi label="Places déclarées" value={totalBeds} icon={BedDouble} tone="blue" hint="disponibles immédiatement"/><Kpi label="Occupation réseau" value={`${averageOccupancy}%`} icon={Activity} tone="amber" hint="moyenne pondérée du prototype"/><Kpi label="Services spécialisés" value={new Set(hospitals.flatMap(item=>item.services||[])).size} icon={Hospital} tone="violet" hint="traumatologie, imagerie, chirurgie…"/></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{hospitals.map(item=><article key={item.id} className="surface p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wider text-emerald-600">{item.id}</div><h3 className="mt-1 font-bold">{item.name}</h3><p className="mt-1 text-xs muted">{item.specialty}</p></div><Status tone={item.reception==='Ouverte'?'green':'amber'}>{item.reception}</Status></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Small label="Places" value={item.beds}/><Small label="Occupation" value={`${item.occupancy}%`}/><Small label="ETA moyenne" value={`${item.eta} min`}/></div><div className="mt-3 flex flex-wrap gap-2">{item.services.map(service=><span key={service} className="chip bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{service}</span>)}</div></article>)}</div></>
}

function HealthSettings({mobileFeedStatus,onNotify}){
  const [tested,setTested]=useState(false)
  const test=()=>{setTested(true);onNotify?.('Canal hospitalier vérifié en mode test','green')}
  return <><PageTitle title="Connexion de l’hôpital" subtitle="Champs prévus pour relier le système d’information hospitalier au backend LOTISEC."/><div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><section className="surface p-5"><div className="flex items-center gap-2"><Network size={18} className="text-emerald-600"/><h3 className="font-semibold">Canal temps réel</h3></div><div className="mt-4 space-y-3"><Config label="API métier" value={portalConfig.apiUrl||'VITE_API_URL — à configurer'}/><Config label="Namespace Socket.IO" value={portalConfig.healthNamespace}/><Config label="Client Keycloak" value={portalConfig.healthClientId}/><Config label="Événement capacité" value={HEALTH_EVENTS.capacityUpdate}/><Config label="Décision d’accueil" value={HEALTH_EVENTS.admissionDecision}/><Config label="Arrivée ambulance" value={HEALTH_EVENTS.expectedArrival}/><Config label="Statut du transfert" value={HEALTH_EVENTS.handoverUpdate}/><Config label="Rôle requis" value={portalConfig.healthRole}/></div><button type="button" onClick={test} className="btn-primary mt-4 w-full !bg-emerald-600"><Radio size={16}/>{tested?'Canal test vérifié':'Tester le canal hospitalier'}</button></section><section className="surface p-5"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-blue-600"/><h3 className="font-semibold">Séparation des données</h3></div><div className="mt-4 space-y-3"><Rule title="Identités masquées" text="Le portail utilise uniquement une référence anonyme de victime."/><Rule title="Périmètre hospitalier" text="Un professionnel ne peut modifier que les capacités de son hôpital."/><Rule title="Traçabilité" text="Acceptations, réorientations et remises sont signées par l’utilisateur connecté."/><Rule title="Mode test indépendant" text="Les essais utilisent un tenant et des événements séparés du flux réel."/></div><div className="mt-4"><Status tone={mobileFeedStatus==='connected'?'green':'blue'}>{mobileFeedStatus==='connected'?'BACKEND RÉEL CONNECTÉ':'ADAPTATEUR PRÊT'}</Status></div></section></div></>
}

function Small({label,value}){return <div className="rounded-xl bg-slate-50 p-2 dark:bg-slate-900"><b className="block truncate text-sm">{value}</b><span className="text-[9px] muted">{label}</span></div>}
function Config({label,value}){return <div className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><code className="mt-1 block break-all text-xs font-semibold text-emerald-700 dark:text-emerald-300">{value}</code></div>}
function Rule({title,text}){return <div className="flex gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-600"/><div><b className="block text-sm">{title}</b><p className="mt-1 text-xs leading-5 muted">{text}</p></div></div>}
