import { useState } from 'react'
import { interventions, routes } from '../data/demo'
import LomeMap from '../components/LomeMap'
import { PageTitle, Status, MiniRoute } from '../components/UI'

const stages=['Affectée','En route','Sur place','Vers le centre de santé','Pris en charge','Terminée']

export default function Interventions({alerts,ambulances,hospitals,mission,auditLog,onAssign,onAdvanceMission,onNavigate,onNotify}){
  const [selectedId,setSelectedId]=useState(interventions[0].id)
  const it=interventions.find(item=>item.id===selectedId)||interventions[0]
  const alert=alerts.find(item=>item.id===(mission?.alertId||it.alertId))||alerts[0]
  const amb=ambulances.find(a=>a.id===mission?.ambulanceId)||ambulances.find(a=>a.id===it.ambulance)||ambulances[0],hosp=hospitals.find(item=>item.id===(mission?.hospitalId||mission?.recommendedHospitalId))||hospitals[0]
  if(!alert) return <><PageTitle title="Interventions" subtitle="Suivi de bout en bout : incident, ambulance, itinéraire et orientation."/><section className="surface p-10 text-center"><h3 className="font-semibold">Aucune intervention active</h3><p className="mt-2 text-sm muted">La prochaine urgence reçue depuis l’application mobile apparaîtra ici automatiquement.</p><button type="button" onClick={()=>onNavigate('map')} className="btn-primary mt-4">Ouvrir la carte opérationnelle</button></section></>
  return <>
    <PageTitle title="Interventions" subtitle="Suivi de bout en bout : incident, ambulance, itinéraire et orientation." action={mission?<button type="button" className="btn-primary" onClick={()=>onNavigate('map')}>Voir le déplacement en direct</button>:<button type="button" className="btn-primary" onClick={()=>onAssign(amb)}>Affecter {amb.id}</button>}/>
    {mission&&<div className="surface mb-4 flex flex-wrap items-center justify-between gap-3 border-blue-200 bg-blue-50/60 p-4 dark:border-blue-900 dark:bg-blue-950/20"><div><div className="font-semibold text-blue-800 dark:text-blue-200">{mission.ambulanceId} est affectée à {mission.alertId}</div><div className="mt-1 text-xs font-semibold text-blue-800 dark:text-blue-200">Itinéraire : {mission.routeMeta?.name||'calcul en cours'}</div><div className="mt-1 text-xs text-blue-700/70 dark:text-blue-300/70">{mission.routeMeta?.engine} · {mission.routeMeta?.distance} km · ETA {mission.routeMeta?.eta} min</div></div><Status tone={mission.status==='Terminée'?'green':'blue'}>{mission.status}</Status></div>}
    <div className="surface mb-4 flex flex-wrap items-center gap-2 p-3">{interventions.map(i=><button type="button" onClick={()=>setSelectedId(i.id)} key={i.id} className={`rounded-xl px-4 py-2 text-sm font-semibold ${i.id===it.id?'bg-blue-600 text-white':'bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700'}`}>{i.id}</button>)}{mission&&mission.status!=='Terminée'&&<button type="button" className="btn-primary ml-auto" onClick={()=>onAdvanceMission()}>Passer à l’étape suivante</button>}</div>
    <div className="grid gap-4 xl:grid-cols-4">
      <Card n="1" title="Incident"><Info label="Type" value={alert.type}/><Info label="Lieu" value={alert.location}/><Info label="Gravité" value={alert.severity}/><Info label="Victimes" value={alert.victims}/></Card>
      <Card n="2" title="Ambulance affectée"><div className="flex justify-between"><div className="font-semibold">{amb.id}</div><Status tone={mission?.status==='Terminée'?'green':'blue'}>{mission?.status||'En route'}</Status></div><Info label="Service" value={amb.provider}/><Info label="ETA" value={`${mission?.routeMeta?.eta||it.eta} min`}/><Info label="Score de décision" value={mission?.ambulanceDecision?.decisionScore?`${mission.ambulanceDecision.decisionScore}%`:'—'}/><Info label="Mise à jour" value={amb.updated}/></Card>
      <Card n="3" title="Itinéraire actuel"><div className="mb-3 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-900 dark:bg-blue-950/30 dark:text-blue-100">{mission?.routeMeta?.name||'Itinéraire opérationnel'}</div><MiniRoute {...routes[0]} distance={mission?.routeMeta?.distance||routes[0].distance} eta={mission?.routeMeta?.eta||routes[0].eta}/><div className="mt-3 space-y-2">{mission?.routeMeta?.steps?.slice(0,3).map((step,index)=><div key={`${step.road}-${index}`} className="flex items-center gap-2 text-[10px] muted"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-blue-100 font-black text-blue-700 dark:bg-blue-950">{index+1}</span><span className="truncate">{step.road}</span></div>)}</div><div className="mt-3"><button type="button" onClick={()=>onNavigate('routing')} className="btn-secondary w-full">Comparer les itinéraires</button></div></Card>
      <Card n="4" title="Orientation centre de santé"><div className="font-semibold">{hosp.name}</div><div className="mt-2 text-sm muted">{hosp.specialty}</div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Info label="ETA" value={`${mission?.hospitalRouteMeta?.eta||hosp.eta} min`}/><Info label="Places" value={hosp.beds}/><Info label="Score" value={mission?.hospitalDecision?.decisionScore?`${mission.hospitalDecision.decisionScore}%`:'—'}/></div><button type="button" onClick={()=>onNavigate('orientation')} className="btn-secondary mt-3 w-full">Comparer les centres</button></Card>
    </div>
    <div className="lotisec-fixed-split mt-4 grid gap-4 2xl:h-[500px] 2xl:grid-cols-[1.35fr_.65fr]"><section className="surface p-4"><h3 className="mb-3 font-semibold">Position & trajet</h3><LomeMap alerts={[alert]} ambulances={[amb]} hospitals={[hosp]} mission={mission} focusAlertId={alert.id} height={420}/></section><section className="surface p-4"><h3 className="font-semibold">Cycle de prise en charge</h3><div className="mt-4 space-y-4">{stages.map((stage,index)=>{const current=Math.max(0,stages.indexOf(mission?.status||'En route'));const done=index<=current;return <div key={stage} className="flex gap-3"><span className={`mt-1 h-3 w-3 rounded-full ${done?'bg-blue-600':'bg-slate-300 dark:bg-slate-700'}`}/><div><div className="text-sm font-medium">{stage}</div><div className="text-xs text-slate-400">{index<current?'Effectué':index===current?'Étape actuelle':'En attente'}</div></div></div>})}</div></section></div>
    <section className="surface mt-4 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Dernières traces de la mission</h3><button type="button" className="text-xs font-semibold text-blue-600" onClick={()=>onNavigate('audit')}>Ouvrir le journal complet</button></div><div className="mt-3 grid gap-2 md:grid-cols-3">{auditLog.slice(0,3).map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900"><b>{item.action}</b><div className="mt-1 text-xs muted">{item.time} · {item.actor}</div></div>)}</div></section>
  </>
}
function Card({n,title,children}){return <section className="surface p-4"><div className="mb-4 flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-full bg-blue-100 text-xs font-bold text-blue-700 dark:bg-blue-950">{n}</span><h3 className="font-semibold">{title}</h3></div><div className="space-y-3">{children}</div></section>}
function Info({label,value}){return <div><div className="text-xs text-slate-400">{label}</div><div className="mt-1 text-sm font-medium">{value}</div></div>}
