import { Activity, Ambulance, CheckCircle2, Clock3, MapPinned, Route, ShieldCheck, TimerReset } from 'lucide-react'
import { Kpi, PageTitle, Status } from '../components/UI'

export default function MissionReports({missions=[],mission,onNavigate}){
  const latest=missions[0]
  const current=mission&&mission.status!=='Terminée'?mission:null
  const etaGain=latest?.etaDelta!=null?Math.max(0,-latest.etaDelta):0
  return <>
    <PageTitle title="Bilans de mission" subtitle="Comparaison entre les prévisions, le déroulement réel ou simulé et les décisions validées." action={<button type="button" onClick={()=>onNavigate('statistics')} className="btn-primary">Exporter le rapport XLSX</button>}/>
    {current&&<section className="surface mb-4 border-blue-200 bg-blue-50/60 p-4 dark:border-blue-900 dark:bg-blue-950/20"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">Mission en cours</div><h3 className="mt-1 font-bold">{current.id} · {current.ambulanceId}</h3><p className="mt-1 text-xs muted">Le bilan définitif sera figé lors du passage au statut « Terminée ».</p></div><div className="flex gap-2"><Status tone="blue">{current.status}</Status><button type="button" onClick={()=>onNavigate('map')} className="btn-secondary">Voir la carte</button></div></div></section>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Missions clôturées" value={missions.length} icon={CheckCircle2} tone="green" hint="Rapports conservés dans cette session"/><Kpi label="ETA prévue" value={latest?`${latest.plannedEta} min`:'—'} icon={Clock3} tone="blue" hint={latest?.initialRoute||'Aucun bilan disponible'}/><Kpi label="Durée observée" value={latest?`${latest.actualEta} min`:'—'} icon={Activity} tone="violet" hint={latest?.dataMode==='test'?'Temps opérationnel simulé':'Télémétrie terrain'}/><Kpi label="Gain après adaptation" value={latest?`${etaGain} min`:'—'} icon={TimerReset} tone="amber" hint={`${latest?.rerouteCount||0} reroutage(s)`}/></div>
    {latest?<><section className="surface mt-4 overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center dark:border-slate-800"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-600">Dernier bilan consolidé</div><h3 className="mt-1 text-lg font-bold">{latest.id}</h3><p className="mt-1 text-xs muted">Incident {latest.incidentId} · ambulance {latest.ambulanceId} · hôpital {latest.hospitalName||latest.hospitalId||'non confirmé'}</p></div><Status tone="green">MISSION TERMINÉE</Status></div><div className="grid gap-4 p-4 lg:grid-cols-3"><Comparison title="Temps de prise en charge" icon={Clock3} planned={`${latest.plannedEta} min`} actual={`${latest.actualEta} min`} delta={formatDelta(latest.etaDelta,'min',true)}/><Comparison title="Distance parcourue" icon={MapPinned} planned={`${latest.plannedDistance} km`} actual={`${latest.actualDistance} km`} delta={formatDelta(latest.distanceDelta,'km')}/><Comparison title="Itinéraire" icon={Route} planned={latest.initialRoute} actual={latest.finalRoute} delta={`${latest.rerouteCount} adaptation(s)`}/></div></section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="surface p-4"><h3 className="font-semibold">Chronologie de prise en charge</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{(latest.stageHistory||[]).map((stage,index)=><div key={`${stage.status}-${index}`} className="flex gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-blue-600 text-xs font-black text-white">{index+1}</span><div><b className="text-sm">{stage.status}</b><div className="mt-1 text-[10px] muted">{formatDate(stage.at)} · {stage.actor||'Système LOTISEC'}</div></div></div>)}</div></section><section className="surface p-4"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-600"/><h3 className="font-semibold">Décisions attribuées</h3></div><Decision title="Affectation ambulance" value={latest.ambulanceValidation?.operator||'—'} detail={latest.ambulanceValidation?.note}/><Decision title="Orientation hospitalière" value={latest.orientationValidation?.operator||'—'} detail={latest.orientationValidation?.note}/><div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800 dark:border-blue-900 dark:bg-blue-950/25 dark:text-blue-200"><b>Source du bilan :</b> {latest.dataMode==='test'?'mode test isolé — résultats du prototype':'flux mobile et télémétrie réels'}.</div></section></div>
    <section className="surface mt-4 overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Historique des bilans</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Mission</th><th>Ambulance</th><th>Hôpital</th><th>Prévu</th><th>Observé</th><th>Reroutages</th><th>Mode</th></tr></thead><tbody>{missions.map(item=><tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{item.id}</td><td>{item.ambulanceId}</td><td>{item.hospitalName||item.hospitalId||'—'}</td><td>{item.plannedEta} min · {item.plannedDistance} km</td><td>{item.actualEta} min · {item.actualDistance} km</td><td>{item.rerouteCount}</td><td><Status tone={item.dataMode==='test'?'blue':'green'}>{item.dataMode==='test'?'TEST':'RÉEL'}</Status></td></tr>)}</tbody></table></div></section></>:<section className="surface mt-4 p-10 text-center"><Ambulance className="mx-auto text-slate-300" size={38}/><h3 className="mt-3 font-semibold">Aucun bilan clôturé</h3><p className="mt-1 text-sm muted">Lancez le mode test ou terminez une intervention pour produire le premier rapport.</p><button type="button" onClick={()=>onNavigate('map')} className="btn-primary mt-4">Ouvrir la carte opérationnelle</button></section>}
  </>
}

function Comparison({title,icon:Icon,planned,actual,delta}){return <article className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center gap-2 text-sm font-semibold"><Icon size={17} className="text-blue-600"/>{title}</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-[10px] muted">Prévision</span><b className="mt-1 block text-sm">{planned}</b></div><div className="rounded-xl bg-emerald-50 p-3 dark:bg-emerald-950/25"><span className="text-[10px] text-emerald-600">Observé</span><b className="mt-1 block text-sm">{actual}</b></div></div><div className="mt-3 text-xs font-semibold text-blue-600">Écart : {delta}</div></article>}
function Decision({title,value,detail}){return <div className="mt-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{title}</div><b className="mt-1 block text-sm">{value}</b><p className="mt-1 text-xs leading-5 muted">{detail||'Aucune justification enregistrée.'}</p></div>}
function formatDelta(value,unit,invert=false){if(value==null)return '—';const positive=Number(value)>0;const label=Math.abs(Number(value)).toFixed(unit==='km'?1:0);if(Number(value)===0)return `0 ${unit}`;return `${positive&&!invert?'+':positive&&invert?'+':'−'}${label} ${unit}`}
function formatDate(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleTimeString('fr-FR')}
