import { useMemo, useState } from 'react'
import { Activity, Ambulance, Building2, CheckCircle2, Clock3, Database, Download, FileBarChart, Filter, Gauge, Landmark, LineChart, Radio, RefreshCw, ShieldCheck, Target, TrendingDown, TrendingUp, UsersRound } from 'lucide-react'
import { Kpi, PageTitle, Status } from '../components/UI'
import { downloadXlsx } from '../lib/xlsx'
import { getPortalGatewayConfig, NATIONAL_EVENTS } from '../services/portalGateway'

const portalConfig=getPortalGatewayConfig()

const territories=[
  {name:'Grand Lomé',region:'Maritime',incidents:1184,severity:28,response:11.8,coverage:91,hospitals:18,trend:-6},
  {name:'Maritime hors Lomé',region:'Maritime',incidents:692,severity:23,response:16.4,coverage:78,hospitals:12,trend:4},
  {name:'Plateaux',region:'Plateaux',incidents:548,severity:31,response:21.7,coverage:64,hospitals:16,trend:8},
  {name:'Centrale',region:'Centrale',incidents:318,severity:25,response:24.2,coverage:59,hospitals:9,trend:-2},
  {name:'Kara',region:'Kara',incidents:267,severity:22,response:22.8,coverage:67,hospitals:11,trend:3},
  {name:'Savanes',region:'Savanes',incidents:182,severity:34,response:29.1,coverage:48,hospitals:7,trend:11},
]

const monthly=[
  {month:'Jan.',incidents:462,deaths:43,injured:681},
  {month:'Fév.',incidents:489,deaths:46,injured:714},
  {month:'Mars',incidents:536,deaths:51,injured:772},
  {month:'Avr.',incidents:558,deaths:57,injured:811},
  {month:'Mai',incidents:571,deaths:59,injured:842},
  {month:'Juin',incidents:575,deaths:58,injured:875},
]

const corridors=[
  {name:'RN1 · Lomé–Tsévié',risk:'Très élevé',score:92,incidents:184,action:'Renforcer les équipes prépositionnées'},
  {name:'Boulevard du 13 Janvier',risk:'Élevé',score:84,incidents:139,action:'Contrôle vitesse et signalisation intelligente'},
  {name:'Axe Atakpamé–Sokodé',risk:'Élevé',score:79,incidents:121,action:'Créer deux points de secours avancés'},
  {name:'RN5 · Kpalimé',risk:'Modéré',score:63,incidents:88,action:'Surveillance des périodes nocturnes'},
]

const sources=[
  {name:'Applications mobiles LOTISEC',freshness:'Temps réel',completeness:96,status:'Opérationnel'},
  {name:'Centres opérationnels',freshness:'Temps réel',completeness:98,status:'Opérationnel'},
  {name:'Réseau hospitalier',freshness:'< 5 min',completeness:87,status:'À renforcer'},
  {name:'Forces de sécurité',freshness:'Quotidien',completeness:81,status:'À renforcer'},
  {name:'Historique DTRF',freshness:'Périodique',completeness:92,status:'Consolidé'},
]

export default function NationalPilotage({view='national-dashboard',alerts=[],ambulances=[],hospitals=[],missionHistory=[],metrics=[],auditLog=[],fog,mobileFeedStatus,onPublishEvent,onNotify}){
  const [period,setPeriod]=useState('1er semestre 2026')
  const [region,setRegion]=useState('Toutes les régions')
  const [lastRefresh,setLastRefresh]=useState(new Date().toLocaleTimeString('fr-FR'))
  const filtered=useMemo(()=>region==='Toutes les régions'?territories:territories.filter(item=>item.region===region),[region])
  const exportReport=(scope='national')=>{
    downloadXlsx(`rapport-pilotage-${scope}-${new Date().toISOString().slice(0,10)}.xlsx`,[
      {name:'Synthèse nationale',rows:[['INDICATEUR','VALEUR','PÉRIODE','LECTURE'],['Accidents recensés',3191,period,'Chiffre utilisé dans le mémoire LOTISEC'],['Décès',314,period,'Agrégat national'],['Blessés',4695,period,'Agrégat national'],['Délai moyen prototype','17,8 min',period,'Simulation fonctionnelle'],['Couverture estimée','72%',period,'Données illustratives du prototype']],headerRows:[0]},
      {name:'Territoires',rows:[['Territoire','Région','Incidents','Cas graves (%)','Réponse moyenne (min)','Couverture (%)','Hôpitaux','Tendance (%)'],...filtered.map(item=>[item.name,item.region,item.incidents,item.severity,item.response,item.coverage,item.hospitals,item.trend])],headerRows:[0],autoFilter:1},
      {name:'Évolution mensuelle',rows:[['Mois','Accidents','Décès','Blessés'],...monthly.map(item=>[item.month,item.incidents,item.deaths,item.injured])],headerRows:[0]},
      {name:'Corridors prioritaires',rows:[['Corridor','Niveau de risque','Score','Incidents','Action recommandée'],...corridors.map(item=>[item.name,item.risk,item.score,item.incidents,item.action])],headerRows:[0],autoFilter:1},
      {name:'Qualité des données',rows:[['Source','Fraîcheur','Complétude (%)','Statut'],...sources.map(item=>[item.name,item.freshness,item.completeness,item.status])],headerRows:[0],autoFilter:1},
    ])
    onPublishEvent?.(NATIONAL_EVENTS.reportGenerated,{scope,period,region,generatedAt:new Date().toISOString(),anonymized:true})
    onNotify?.('Rapport national XLSX téléchargé','green')
  }
  const refresh=()=>{setLastRefresh(new Date().toLocaleTimeString('fr-FR'));onNotify?.('Indicateurs nationaux recalculés','green')}
  const common={alerts,ambulances,hospitals,missionHistory,metrics,auditLog,fog,mobileFeedStatus,period,setPeriod,region,setRegion,filtered,lastRefresh,refresh,exportReport,onNotify}
  if(view==='national-territories') return <Territories {...common}/>
  if(view==='national-performance') return <Performance {...common}/>
  if(view==='national-analytics') return <Analytics {...common}/>
  if(view==='national-reports') return <Reports {...common}/>
  if(view==='national-data') return <DataQuality {...common}/>
  if(view==='national-governance') return <Governance {...common}/>
  return <NationalDashboard {...common}/>
}

function NationalDashboard({alerts,ambulances,hospitals,period,setPeriod,lastRefresh,refresh,exportReport}){
  return <>
    <PageTitle title="Pilotage national des urgences routières" subtitle="Vue consolidée destinée aux ministères, directions nationales et responsables de politiques publiques." action={<div className="flex flex-wrap gap-2"><select value={period} onChange={event=>setPeriod(event.target.value)} className="input !w-auto"><option>1er semestre 2026</option><option>Année 2025</option><option>30 derniers jours</option></select><button type="button" onClick={()=>exportReport('national')} className="btn-primary !bg-violet-700"><Download size={16}/>Rapport national</button></div>}/>
    <section className="surface mb-4 overflow-hidden border-violet-200 dark:border-violet-900"><div className="bg-gradient-to-r from-[#312e81] via-violet-700 to-blue-600 p-5 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><Landmark size={23}/></span><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-violet-100">Cellule interministérielle LOTISEC</div><h3 className="mt-1 text-xl font-bold">Situation nationale consolidée</h3><p className="mt-1 text-xs text-violet-100">Santé · Sécurité · Transports · Collectivités territoriales</p></div></div><button type="button" onClick={refresh} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/15 px-4 py-2.5 text-xs font-semibold hover:bg-white/20"><RefreshCw size={15}/>Actualisé à {lastRefresh}</button></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Accidents recensés" value="3 191" icon={Activity} tone="red" hint="1er semestre 2026 · référence du mémoire"/><Kpi label="Décès" value="314" icon={UsersRound} tone="violet" hint="agrégat national de la période"/><Kpi label="Blessés" value="4 695" icon={UsersRound} tone="amber" hint="agrégat national de la période"/><Kpi label="Couverture LOTISEC" value="72%" icon={Target} tone="green" hint="estimation illustrative du prototype"/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="surface p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Évolution mensuelle</h3><p className="mt-1 text-xs muted">Accidents enregistrés sur la période de référence.</p></div><Status tone="violet">{period}</Status></div><div className="mt-6 flex h-64 items-end gap-3">{monthly.map(item=>{const height=Math.round(item.incidents/600*100);return <div key={item.month} className="flex h-full flex-1 flex-col justify-end"><div className="mb-2 text-center text-xs font-bold">{item.incidents}</div><div className="group relative rounded-t-xl bg-gradient-to-t from-violet-800 to-blue-400 transition hover:from-violet-700" style={{height:`${height}%`}}><div className="absolute inset-x-0 top-2 hidden text-center text-[9px] text-white group-hover:block">{item.deaths} décès</div></div><div className="mt-2 text-center text-[10px] font-semibold muted">{item.month}</div></div>})}</div></section><section className="surface p-5"><h3 className="font-semibold">Réseau opérationnel actuel</h3><div className="mt-4 space-y-3"><NetworkLine icon={Ambulance} label="Ambulances suivies" value={ambulances.length} detail={`${ambulances.filter(item=>item.status==='Disponible').length} disponibles`}/><NetworkLine icon={Building2} label="Hôpitaux connectés" value={hospitals.length} detail={`${hospitals.reduce((sum,item)=>sum+Number(item.beds||0),0)} places déclarées`}/><NetworkLine icon={Radio} label="Incidents de session" value={alerts.length} detail="flux opérationnel actif"/><NetworkLine icon={Database} label="Qualité moyenne" value="91%" detail="complétude des données"/></div></section></div>
    <section className="surface mt-4 p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Priorités de décision</h3><p className="mt-1 text-xs muted">Recommandations issues des indicateurs et des zones à risque du prototype.</p></div><Status tone="amber">4 ACTIONS</Status></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{corridors.map((item,index)=><article key={item.name} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><span className="text-[9px] font-black uppercase tracking-wider text-violet-600">Priorité {index+1}</span><b className="mt-2 block text-sm">{item.name}</b><p className="mt-2 text-xs leading-5 muted">{item.action}</p><div className="mt-3 flex items-center justify-between"><Status tone={item.score>85?'red':'amber'}>{item.risk}</Status><b className="text-sm">{item.score}/100</b></div></article>)}</div></section>
  </>
}

function Territories({region,setRegion,filtered}){
  const max=Math.max(...filtered.map(item=>item.incidents),1)
  return <><PageTitle title="Territoires et zones prioritaires" subtitle="Comparer la charge d’accidents, la couverture des secours et les capacités territoriales." action={<div className="flex items-center gap-2"><Filter size={16} className="text-violet-600"/><select value={region} onChange={event=>setRegion(event.target.value)} className="input !w-auto"><option>Toutes les régions</option><option>Maritime</option><option>Plateaux</option><option>Centrale</option><option>Kara</option><option>Savanes</option></select></div>}/><div className="grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><section className="surface p-5"><h3 className="font-semibold">Volume par territoire</h3><div className="mt-5 space-y-5">{filtered.map(item=><div key={item.name}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="font-semibold">{item.name}</span><b>{item.incidents} incidents</b></div><div className="h-3 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-3 rounded-full ${item.severity>30?'bg-red-500':item.severity>25?'bg-amber-500':'bg-violet-600'}`} style={{width:`${Math.max(8,item.incidents/max*100)}%`}}/></div><div className="mt-1 flex justify-between text-[10px] muted"><span>{item.severity}% de cas graves</span><span>Réponse moyenne {item.response} min</span></div></div>)}</div></section><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Matrice de couverture</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Territoire</th><th>Couverture</th><th>Hôpitaux</th><th>Tendance</th><th>Priorité</th></tr></thead><tbody>{filtered.map(item=><tr key={item.name} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{item.name}</td><td>{item.coverage}%</td><td>{item.hospitals}</td><td><span className={`inline-flex items-center gap-1 font-semibold ${item.trend>0?'text-red-600':'text-emerald-600'}`}>{item.trend>0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {Math.abs(item.trend)}%</span></td><td><Status tone={item.coverage<55?'red':item.coverage<70?'amber':'green'}>{item.coverage<55?'Urgente':item.coverage<70?'À renforcer':'Maîtrisée'}</Status></td></tr>)}</tbody></table></div></section></div><section className="surface mt-4 border-amber-200 bg-amber-50/60 p-4 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200"><b>Lecture scientifique :</b> la répartition territoriale détaillée est illustrative et sert à démontrer le fonctionnement du tableau de pilotage. Elle devra être alimentée par les données officielles validées avant tout usage décisionnel réel.</section></>
}

function Performance({ambulances,hospitals,metrics}){
  const indicators=[
    {label:'Réception → validation',value:'1,4 min',target:'≤ 2 min',score:92,tone:'bg-emerald-500'},
    {label:'Validation → affectation',value:'2,1 min',target:'≤ 3 min',score:88,tone:'bg-emerald-500'},
    {label:'Affectation → arrivée',value:'14,3 min',target:'≤ 15 min',score:81,tone:'bg-blue-500'},
    {label:'Arrivée → orientation',value:'5,8 min',target:'≤ 7 min',score:86,tone:'bg-violet-500'},
  ]
  return <><PageTitle title="Performance de la chaîne de secours" subtitle="Suivre les délais, la disponibilité et la continuité de service de bout en bout."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Délai global moyen" value="17,8 min" icon={Clock3} tone="blue" hint="prototype fonctionnel"/><Kpi label="Ambulances mobilisables" value={`${ambulances.filter(item=>item.status==='Disponible').length}/${ambulances.length}`} icon={Ambulance} tone="green" hint="session opérationnelle"/><Kpi label="Places hospitalières" value={hospitals.reduce((sum,item)=>sum+Number(item.beds||0),0)} icon={Building2} tone="violet" hint="déclaration actuelle"/><Kpi label="Mesures techniques" value={metrics.length} icon={Gauge} tone="amber" hint="traces de la session"/></div><section className="surface mt-4 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Objectifs de service</h3><Status tone="green">CHAÎNE SURVEILLÉE</Status></div><div className="mt-5 grid gap-4 md:grid-cols-2">{indicators.map(item=><article key={item.label} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">{item.label}</b><p className="mt-1 text-xs muted">Objectif national : {item.target}</p></div><b className="text-lg">{item.value}</b></div><div className="mt-4 h-2.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-2.5 rounded-full ${item.tone}`} style={{width:`${item.score}%`}}/></div><div className="mt-1 text-right text-[10px] muted">{item.score}% de conformité</div></article>)}</div></section></>
}

function Analytics(){
  const categories=[['Motos',42,'bg-red-500'],['Véhicules légers',31,'bg-violet-600'],['Piétons',14,'bg-amber-500'],['Poids lourds',8,'bg-blue-500'],['Autres',5,'bg-slate-400']]
  return <><PageTitle title="Analyses et tendances" subtitle="Identifier les profils d’accidents et les corridors nécessitant une intervention publique."/><div className="grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><section className="surface p-5"><h3 className="font-semibold">Répartition illustrative par usager</h3><div className="mt-5 space-y-4">{categories.map(([label,value,tone])=><div key={label}><div className="mb-1.5 flex justify-between text-sm"><span>{label}</span><b>{value}%</b></div><div className="h-3 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-3 rounded-full ${tone}`} style={{width:`${value}%`}}/></div></div>)}</div></section><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Corridors à risque</h3><p className="mt-1 text-xs muted">Classement explicable selon fréquence, gravité, délai d’accès et couverture.</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{corridors.map((item,index)=><div key={item.name} className="p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-100 font-black text-violet-700">{index+1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.name}</b><Status tone={item.score>85?'red':'amber'}>{item.score}/100</Status></div><p className="mt-1 text-xs muted">{item.incidents} incidents · {item.action}</p></div></div></div>)}</div></section></div><section className="surface mt-4 p-5"><div className="flex gap-3"><LineChart size={21} className="shrink-0 text-violet-600"/><div><h3 className="font-semibold">Aide à la décision, pas décision automatique</h3><p className="mt-1 text-sm leading-6 muted">LOTISEC met en évidence les tendances et explique les facteurs du classement. La validation des politiques, budgets et implantations reste sous la responsabilité des autorités compétentes.</p></div></div></section></>
}

function Reports({exportReport}){
  const reports=[
    {title:'Situation semestrielle nationale',detail:'Accidents, victimes, couverture et performance',period:'S1 2026',tone:'violet'},
    {title:'Couverture territoriale des secours',detail:'Ambulances, délais et zones sous-desservies',period:'Août 2026',tone:'blue'},
    {title:'Capacités hospitalières',detail:'Places, spécialités et tension du réseau',period:'Temps réel',tone:'green'},
    {title:'Corridors routiers prioritaires',detail:'Scores de risque et actions recommandées',period:'S1 2026',tone:'amber'},
  ]
  return <><PageTitle title="Rapports décisionnels" subtitle="Produire des documents structurés pour le suivi interministériel et la soutenance." action={<button type="button" onClick={()=>exportReport('complet')} className="btn-primary !bg-violet-700"><Download size={16}/>Télécharger le rapport complet</button>}/><div className="grid gap-4 md:grid-cols-2">{reports.map((item,index)=><article key={item.title} className="surface p-5"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${item.tone==='violet'?'bg-violet-100 text-violet-700':item.tone==='blue'?'bg-blue-100 text-blue-700':item.tone==='green'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}><FileBarChart size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.title}</b><Status tone={item.tone}>{item.period}</Status></div><p className="mt-1 text-xs leading-5 muted">{item.detail}</p></div></div><button type="button" onClick={()=>exportReport(`rapport-${index+1}`)} className="btn-secondary mt-4 w-full"><Download size={15}/>Exporter en XLSX</button></article>)}</div></>
}

function DataQuality({lastRefresh,refresh}){
  const average=Math.round(sources.reduce((sum,item)=>sum+item.completeness,0)/sources.length)
  return <><PageTitle title="Qualité et provenance des données" subtitle="Distinguer les données vérifiées, les flux temps réel et les valeurs illustratives du prototype." action={<button type="button" onClick={refresh} className="btn-primary !bg-violet-700"><RefreshCw size={16}/>Recalculer la qualité</button>}/><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Complétude moyenne" value={`${average}%`} icon={CheckCircle2} tone="green" hint={`recalculée à ${lastRefresh}`}/><Kpi label="Sources connectées" value={sources.length} icon={Database} tone="blue" hint="opérationnelles et historiques"/><Kpi label="Anomalies ouvertes" value="3" icon={Activity} tone="amber" hint="coordonnées ou délais incomplets"/></div><section className="surface mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Source</th><th>Fraîcheur</th><th>Complétude</th><th>Statut</th><th>Qualification</th></tr></thead><tbody>{sources.map(item=><tr key={item.name} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{item.name}</td><td>{item.freshness}</td><td><div className="flex items-center gap-2"><div className="h-2 w-24 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded-full bg-violet-600" style={{width:`${item.completeness}%`}}/></div><b>{item.completeness}%</b></div></td><td><Status tone={item.status==='Opérationnel'||item.status==='Consolidé'?'green':'amber'}>{item.status}</Status></td><td className="text-xs muted">{item.name.includes('mobile')?'Temps réel terrain':item.name.includes('DTRF')?'Historique officiel':'Partenaire institutionnel'}</td></tr>)}</tbody></table></div></section></>
}

function Governance({auditLog,fog,mobileFeedStatus}){
  return <><PageTitle title="Gouvernance, confidentialité et accès" subtitle="Garantir que le pilotage national utilise des données agrégées, anonymisées et traçables."/><div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><section className="surface p-5"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-violet-600"/><h3 className="font-semibold">Principes appliqués</h3></div><div className="mt-4 space-y-3"><GovernanceRule title="Aucune identité de victime" text="Les ministères voient uniquement des agrégats territoriaux et temporels."/><GovernanceRule title="Accès par rôle Keycloak" text={`Le rôle ${portalConfig.nationalRole} limite les vues et les exports.`}/><GovernanceRule title="Traçabilité des exports" text="Chaque rapport est horodaté avec l’utilisateur, le périmètre et la période."/><GovernanceRule title="Séparation test / réel" text="Les statistiques de démonstration sont étiquetées et ne fusionnent jamais avec les données officielles."/></div></section><section className="surface p-5"><h3 className="font-semibold">État de la gouvernance technique</h3><div className="mt-4 space-y-3"><State label="Journal d’audit" value={`${auditLog.length} événement(s)`} tone="green"/><State label="Continuité Fog" value={fog?.effectiveMode==='offline'?'Locale active':fog?.quality?.label||'Opérationnelle'} tone={fog?.effectiveMode==='offline'?'amber':'green'}/><State label="Flux mobile réel" value={mobileFeedStatus==='connected'?'Connecté':'Adaptateur prêt'} tone={mobileFeedStatus==='connected'?'green':'blue'}/><State label="Namespace national" value={portalConfig.nationalNamespace} tone="violet"/><State label="Client Keycloak" value={portalConfig.nationalClientId} tone="blue"/><State label="Données personnelles" value="Non exposées" tone="green"/></div></section></div><section className="surface mt-4 border-violet-200 bg-violet-50/50 p-5 dark:border-violet-900 dark:bg-violet-950/20"><div className="flex gap-3"><Landmark size={21} className="shrink-0 text-violet-700"/><div><b className="text-sm">Périmètre de la démonstration</b><p className="mt-1 text-xs leading-5 muted">Le tableau de pilotage valide la cohérence fonctionnelle et l’architecture multi-acteurs. Les indicateurs territoriaux détaillés restent illustratifs tant que les flux institutionnels complets ne sont pas connectés.</p></div></div></section></>
}

function NetworkLine({icon:Icon,label,value,detail}){return <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-100 text-violet-700"><Icon size={17}/></span><div className="min-w-0 flex-1"><b className="block text-sm">{label}</b><span className="text-[10px] muted">{detail}</span></div><b className="text-lg">{value}</b></div>}
function GovernanceRule({title,text}){return <div className="flex gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-emerald-600"/><div><b className="block text-sm">{title}</b><p className="mt-1 text-xs leading-5 muted">{text}</p></div></div>}
function State({label,value,tone}){return <div className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-sm font-semibold">{label}</span><Status tone={tone}>{value}</Status></div>}
