import { useEffect, useMemo, useState } from 'react'
import { BedDouble, CheckCircle2, CircleAlert, ListTree, LoaderCircle, LocateFixed, Maximize2, Minimize2, Navigation, Radio, RotateCcw, Smartphone, TrafficCone } from 'lucide-react'
import LomeMap from '../components/LomeMap'
import { PageTitle, Status } from '../components/UI'
import { playMapExpand } from '../lib/sound'
import { useMissionProgress } from '../hooks/useMissionProgress'

export default function OperationalMap({alerts,ambulances,hospitals,selectedAlertId,onSelectAlert,mission,ambulanceRanking,hospitalRanking,onAssign,onAdvanceMission,onResetMission,onSimulateCongestion,onConfirmOrientation,onNavigate,onSimulateMobile,mobileFeedStatus,dataMode='test'}){
  const rankedAmbulances=ambulanceRanking?.length?ambulanceRanking:ambulances
  const rankedHospitals=hospitalRanking?.length?hospitalRanking:hospitals
  const [selectedAmbulanceId,setSelectedAmbulanceId]=useState(ambulances.find(a=>a.status==='Disponible')?.id||ambulances[0].id)
  const [selectedHospitalId,setSelectedHospitalId]=useState(hospitals[0].id)
  const [layers,setLayers]=useState({Incidents:true,Ambulances:true,Hôpitaux:true,Trafic:true,Itinéraires:true})
  const [mapExpanded,setMapExpanded]=useState(false)
  const [followAmbulance,setFollowAmbulance]=useState(false)
  const selectedAlert=alerts.find(a=>a.id===selectedAlertId)||alerts[0]||{id:'',type:'Aucun incident actif',severity:'En attente',location:'Le flux mobile réel est prêt à recevoir un signalement.',victims:0,vehicles:0,accuracy:'—',status:'En attente',lat:6.1375,lng:1.2123}
  const selectedAmbulance=rankedAmbulances.find(a=>a.id===selectedAmbulanceId)||rankedAmbulances[0]
  const selectedHospital=rankedHospitals.find(h=>h.id===selectedHospitalId)||rankedHospitals[0]
  const missionHospital=rankedHospitals.find(h=>h.id===(mission?.hospitalId||mission?.recommendedHospitalId))
  const liveAmbulances=useMemo(()=>rankedAmbulances.map(a=>mission?.ambulanceId===a.id?{...a,status:mission.status}:a),[rankedAmbulances,mission])
  const displayedAlerts=layers.Incidents?alerts:[]
  const displayedAmbulances=layers.Ambulances?liveAmbulances:[]
  const displayedHospitals=layers.Hôpitaux?rankedHospitals:[]

  useEffect(()=>{if(selectedAlertId&&alerts.some(a=>a.id===selectedAlertId)) onSelectAlert(alerts.find(a=>a.id===selectedAlertId))},[selectedAlertId])
  useEffect(()=>{if(missionHospital) setSelectedHospitalId(missionHospital.id)},[missionHospital?.id])
  useEffect(()=>{const recommended=rankedAmbulances.find(item=>item.recommended);if(!mission&&recommended)setSelectedAmbulanceId(recommended.id)},[selectedAlertId,mission?.id])
  useEffect(()=>{if(mission?.id)setFollowAmbulance(true)},[mission?.id])

  return <>
    <PageTitle title="Carte opérationnelle" subtitle="OpenStreetMap, incidents mobiles, ressources, capacités hospitalières et itinéraires en direct." action={<div className="flex flex-wrap gap-2"><button type="button" disabled={dataMode!=='test'} className="btn-secondary disabled:cursor-not-allowed disabled:opacity-50" onClick={onSimulateMobile}><Smartphone size={17}/>Tester un signalement</button>{mission&&<button type="button" className="btn-secondary text-red-600" onClick={onResetMission}><RotateCcw size={16}/>Réinitialiser la mission</button>}<button type="button" disabled={!selectedAlert.id||Boolean(mission&&mission.status!=='Terminée')} className="btn-primary disabled:cursor-not-allowed disabled:opacity-50" onClick={()=>onAssign(selectedAmbulance,selectedAlert.id)}>{mission?.routeState==='loading'?<LoaderCircle size={16} className="animate-spin"/>:null}Examiner {selectedAmbulance.id}</button></div>}/>
    {mission&&<MissionBanner mission={mission} hospital={missionHospital} onNavigate={onNavigate} onReset={onResetMission}/>}
    {mission?.status==='Terminée'&&<MissionSummary mission={mission} hospital={missionHospital} alert={selectedAlert} onNavigate={onNavigate}/>}
    <div className="grid items-start gap-4 2xl:grid-cols-[minmax(0,1fr)_390px]">
      <section className={`surface flex flex-col p-3 ${mapExpanded?'fixed inset-3 z-[80] shadow-2xl':'2xl:sticky 2xl:top-0 2xl:h-[calc(100vh-9rem)] 2xl:min-h-[560px] 2xl:max-h-[700px]'}`}>
        <div className="mb-3 flex flex-wrap items-center gap-2 text-xs">
          {Object.keys(layers).map(label=><label key={label} className={`chip cursor-pointer ${layers[label]?'bg-blue-50 text-blue-700 dark:bg-blue-950/40':'bg-slate-100 text-slate-400 dark:bg-slate-800'}`}><input checked={layers[label]} onChange={()=>setLayers(current=>({...current,[label]:!current[label]}))} type="checkbox"/> {label}</label>)}
          <span className={`chip ${dataMode==='real'&&mobileFeedStatus==='connected'?'bg-emerald-100 text-emerald-700':'bg-blue-100 text-blue-700 dark:bg-blue-950/30 dark:text-blue-300'}`}><Radio size={13} className={dataMode==='real'&&mobileFeedStatus==='connected'?'animate-pulse':''}/>{dataMode==='test'?'Mode test isolé':mobileFeedStatus==='connected'?'Flux mobile réel connecté':'Flux mobile réel en attente'}</span>
          {mission?.congestion&&<span className="chip bg-red-100 text-red-700 dark:bg-red-950/40 dark:text-red-300"><TrafficCone size={13}/>Congestion détectée · alternative annoncée</span>}
          {mission&&<button type="button" onClick={()=>setFollowAmbulance(value=>!value)} className={`chip ml-auto ${followAmbulance?'bg-blue-100 text-blue-700':'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}><Navigation size={13}/>{followAmbulance?'Suivi ambulance actif':'Suivi ambulance libre'}</button>}
          <button type="button" className="btn-secondary ml-auto !px-3 !py-1.5" onClick={()=>{playMapExpand();setMapExpanded(value=>!value)}}>{mapExpanded?<><Minimize2 size={15}/>Réduire la carte</>:<><Maximize2 size={15}/>Agrandir la carte</>}</button>
        </div>
        <div className={`min-h-[650px] flex-1 overflow-hidden rounded-xl 2xl:min-h-0 ${mapExpanded?'!min-h-0':''}`}><LomeMap alerts={displayedAlerts} ambulances={displayedAmbulances} hospitals={displayedHospitals} mission={mission} followAmbulance={followAmbulance} routeVariants={Boolean(mission&&['Analyse trafic','Affectée'].includes(mission.status))} showRoute={layers.Itinéraires} showTraffic={layers.Trafic} focusAlertId={selectedAlert.id} onSelectAlert={onSelectAlert} onSelectHospital={hospital=>setSelectedHospitalId(hospital.id)} height="100%"/></div>
      </section>
      <aside className="lotisec-scroll-panel space-y-4 2xl:h-[calc(100vh-9rem)] 2xl:min-h-[560px] 2xl:max-h-[700px] 2xl:overflow-y-auto 2xl:overscroll-contain 2xl:pr-2">
        <section className="surface p-4">
          <div className="flex justify-between gap-2"><div><div className="text-[10px] font-bold tracking-wider text-red-600">INCIDENT SÉLECTIONNÉ</div><h3 className="mt-1 font-semibold">{selectedAlert.type}</h3></div><Status tone="red">{selectedAlert.severity}</Status></div>
          <div className="mt-2 flex items-start gap-2 text-sm muted"><LocateFixed size={16} className="mt-0.5 shrink-0"/>{selectedAlert.location}</div>
          <div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs"><Stat label="Victimes" value={selectedAlert.victims}/><Stat label="Véhicules" value={selectedAlert.vehicles||1}/><Stat label="GPS" value={selectedAlert.accuracy||'8 m'}/><Stat label="État" value={selectedAlert.status||'Reçu'}/></div>
          <div className="mt-3 rounded-xl border border-slate-100 bg-slate-50 p-3 text-[10px] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2 font-bold text-emerald-700 dark:text-emerald-300"><CheckCircle2 size={14}/>Message mobile traçable</div><div className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 muted"><span>Événement</span><b className="truncate text-slate-700 dark:text-slate-200">{selectedAlert.eventName||'incident:new'}</b><span>Transport</span><b className="truncate text-slate-700 dark:text-slate-200">{selectedAlert.transport||'Application mobile'}</b><span>Réception</span><b className="text-slate-700 dark:text-slate-200">{formatReceivedAt(selectedAlert)}</b><span>Traitement</span><b className="text-emerald-600">{selectedAlert.messageState||'Reçu et validé'}</b></div></div>
          <button type="button" className="btn-secondary mt-4 w-full" onClick={()=>onNavigate('interventions')}>Voir l’intervention</button>
        </section>
        <section className="surface p-4">
          <h3 className="font-semibold">Affecter une ambulance</h3><p className="mt-1 text-xs muted">Choisissez une unité disponible pour lancer son déplacement.</p>
          <div className="mt-3 space-y-2">{liveAmbulances.map(ambulance=>{const active=selectedAmbulanceId===ambulance.id,assigned=mission?.ambulanceId===ambulance.id;return <button type="button" key={ambulance.id} onClick={()=>setSelectedAmbulanceId(ambulance.id)} className={`w-full rounded-xl border p-3 text-left text-sm transition ${ambulance.recommended?'border-blue-400 bg-blue-50/80 ring-2 ring-blue-500/10 dark:bg-blue-950/30':active?'border-blue-500 bg-blue-50/60 dark:bg-blue-950/30':'border-slate-200 hover:border-blue-300 dark:border-slate-700'}`}><div className="flex items-center justify-between gap-2"><div><div className="flex items-center gap-2"><b>{ambulance.id}</b>{ambulance.recommended&&<span className="rounded-full bg-blue-600 px-2 py-0.5 text-[9px] font-black uppercase text-white">Recommandée · {ambulance.decisionScore}%</span>}</div><div className="text-xs muted">{ambulance.provider}</div></div><Status tone={assigned?'blue':ambulance.status==='Disponible'?'green':'amber'}>{assigned?'En déplacement':ambulance.status}</Status></div><div className="mt-2 text-[10px] muted">{ambulance.decisionReason||`${ambulance.eta} min · ${ambulance.equipment||'équipe standard'}`}</div></button>})}</div>
          <button type="button" disabled={!selectedAlert.id||Boolean(mission&&mission.status!=='Terminée')} className="btn-primary mt-3 w-full disabled:cursor-not-allowed disabled:opacity-50" onClick={()=>onAssign(selectedAmbulance,selectedAlert.id)}>{mission?.routeState==='loading'?<><LoaderCircle size={16} className="animate-spin"/>Analyse du trafic…</>:'Examiner et valider l’affectation'}</button>
          {mission&&<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={mission.routeState==='loading'||mission.status!=='En route'} className="btn-secondary text-red-600 disabled:opacity-50" onClick={onSimulateCongestion}><TrafficCone size={15}/>Nouvel aléa trafic</button><button type="button" disabled={mission.routeState==='loading'||mission.status==='Terminée'} className="btn-secondary disabled:opacity-50" onClick={()=>onAdvanceMission()}>{mission.status==='Sur place'?'Orientation':'Étape suivante'}</button></div>}
        </section>
        {mission&&<RouteSheet mission={mission} onNavigate={onNavigate}/>}
        <section className="surface p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Hôpitaux disponibles</h3><BedDouble size={18} className="text-emerald-600"/></div><div className="mt-3 space-y-2">{rankedHospitals.map(hospital=><button type="button" key={hospital.id} onClick={()=>setSelectedHospitalId(hospital.id)} className={`w-full rounded-xl border p-3 text-left text-sm transition ${hospital.recommended?'border-emerald-500 bg-gradient-to-r from-emerald-700 to-emerald-500 text-white shadow-md':selectedHospital.id===hospital.id?'border-emerald-500 bg-emerald-50/60 dark:bg-emerald-950/20':'border-slate-200 dark:border-slate-700'}`}><div className="flex items-center justify-between gap-2"><div><div className="flex items-center gap-2"><b>{hospital.name}</b>{hospital.recommended&&<span className="rounded-full border border-white/30 bg-white/15 px-2 py-0.5 text-[9px] font-black uppercase">✓ {hospital.decisionScore}%</span>}</div><div className={`text-xs ${hospital.recommended?'text-emerald-50':'muted'}`}>{hospital.specialty} · {hospital.decisionEta||hospital.eta} min</div></div><span className={`rounded-lg px-2 py-1 text-xs font-bold ${hospital.recommended?'bg-white text-emerald-700':'bg-emerald-100 text-emerald-700'}`}>{hospital.beds} places</span></div><div className={`mt-2 text-[10px] ${hospital.recommended?'text-emerald-50':'muted'}`}>{hospital.decisionReason}</div></button>)}</div><button type="button" className="btn-primary mt-3 w-full" onClick={()=>onConfirmOrientation(selectedHospital)}>Examiner et confirmer {selectedHospital.name}</button><button type="button" className="btn-secondary mt-2 w-full" onClick={()=>onNavigate('orientation')}>Comparer les capacités</button></section>
      </aside>
    </div>
  </>
}

function Stat({label,value}){return <div className="rounded-xl bg-slate-50 p-2 dark:bg-slate-800"><b className="block text-sm">{value}</b><span className="muted">{label}</span></div>}

function RouteSheet({mission,onNavigate}){
  const telemetry=useMissionProgress(mission)
  const steps=(mission.routeMeta?.steps||[]).slice(0,5)
  return <section className="surface overflow-hidden">
    <div className="border-b border-slate-100 bg-gradient-to-r from-blue-700 to-blue-500 p-4 text-white dark:border-slate-800"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-blue-100"><ListTree size={15}/>Navigation en direct</div><div className="mt-1 text-sm font-bold leading-5">{mission.routeMeta?.name||'Itinéraire opérationnel'}</div><div className="mt-2 grid grid-cols-4 gap-2 text-center text-[9px]"><LiveStat label="Reste" value={`${telemetry?.distanceRemaining||0} km`}/><LiveStat label="ETA" value={`${telemetry?.etaRemaining||0} min`}/><LiveStat label="Vitesse" value={`${telemetry?.speed||0} km/h`}/><LiveStat label="Progression" value={`${telemetry?.progress||0}%`}/></div></div>
    <div className="p-4">{telemetry?.nextStep&&<div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3 dark:border-blue-900 dark:bg-blue-950/25"><div className="text-[9px] font-black uppercase tracking-wider text-blue-600">Prochaine instruction · ≈ {formatDistance(telemetry.nextDistance)}</div><div className="mt-1 text-xs font-bold text-blue-900 dark:text-blue-100">{telemetry.nextStep.instruction}</div></div>}<div className="space-y-3">{steps.map((step,index)=>{const active=index===telemetry?.stepIndex,done=index<(telemetry?.stepIndex||0);return <div key={`${step.road}-${index}`} className={`flex gap-3 rounded-xl p-2 ${active?'bg-blue-50 ring-1 ring-blue-200 dark:bg-blue-950/25 dark:ring-blue-900':''}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-[10px] font-black ${done?'bg-sky-400 text-white':active?'bg-blue-700 text-white':'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200'}`}>{done?'✓':index+1}</span><div className="min-w-0"><div className="truncate text-xs font-bold">{step.road}</div><div className="mt-0.5 text-[10px] leading-4 muted">{step.instruction} · {step.distance}</div></div></div>})}</div><button type="button" className="btn-secondary mt-4 w-full" onClick={()=>onNavigate('routing')}>Voir toutes les étapes</button></div>
  </section>
}

function LiveStat({label,value}){return <div className="rounded-lg bg-white/10 px-1 py-2"><b className="block text-[10px]">{value}</b><span className="text-[8px] text-blue-100">{label}</span></div>}
function formatDistance(distance){if(!distance)return '0 m';return distance<1?`${Math.max(50,Math.round(distance*1000/50)*50)} m`:`${distance.toFixed(1).replace('.',',')} km`}
function formatReceivedAt(alert){if(!alert.receivedAt)return alert.received||'À l’instant';const date=new Date(alert.receivedAt);return Number.isNaN(date.getTime())?alert.received:date.toLocaleTimeString('fr-FR')}

const missionSteps=['Analyse trafic','Affectée','En route','Sur place','Orientation hospitalière','Vers le centre de santé','Pris en charge','Terminée']

function MissionBanner({mission,hospital,onNavigate,onReset}){
  const telemetry=useMissionProgress(mission)
  const status=mission.status|| (telemetry?.progress>=100?'Sur place':'En route')
  const currentIndex=Math.max(0,missionSteps.indexOf(status))
  return <section className={`surface mb-4 overflow-hidden ${mission.routeState==='fallback'?'border-amber-300':mission.congestion?'border-red-300':'border-blue-200'}`}>
    {mission.routeState==='loading'&&<div className="flex items-center gap-3 bg-blue-700 px-4 py-3 text-white"><LoaderCircle size={20} className="animate-spin"/><div><div className="text-sm font-bold">Analyse du trafic avant départ</div><div className="text-xs text-blue-100">L’ambulance reste immobile pendant la comparaison des axes et des alternatives.</div></div></div>}
    {mission.preDeparture?.state==='rerouted'&&<div className="flex items-start gap-3 bg-red-600 px-4 py-3 text-white"><TrafficCone size={20} className="mt-0.5 shrink-0"/><div><div className="text-sm font-bold">Congestion détectée avant le mouvement</div><div className="mt-0.5 text-xs text-red-50">{mission.preDeparture.congestedRoad} écarté · trajet retenu : {mission.preDeparture.selectedRouteName}</div></div><span className="ml-auto shrink-0 rounded-full bg-white/15 px-3 py-1 text-[9px] font-black uppercase">Alternative validée</span></div>}
    {mission.routeState==='fallback'&&<div className="flex items-start gap-3 bg-amber-500 px-4 py-3 text-amber-950"><CircleAlert size={20}/><div><div className="text-sm font-bold">Mode de continuité activé</div><div className="text-xs">Le service distant est indisponible ; un itinéraire local de secours est utilisé.</div></div></div>}
    <div className="p-4">
    <div className="grid gap-3 lg:grid-cols-[1fr_auto_auto] lg:items-center">
      <div><div className="flex items-center gap-2 font-semibold text-blue-800 dark:text-blue-200"><span className={`h-2.5 w-2.5 rounded-full bg-blue-600 ${status!=='Terminée'?'animate-pulse':''}`}/>{mission.ambulanceId} · {status} {mission.ambulanceDecision?.decisionScore&&<span className="rounded-full bg-blue-600 px-2 py-0.5 text-[9px] text-white">Score {mission.ambulanceDecision.decisionScore}%</span>}</div><div className="mt-1 text-xs font-semibold text-blue-800 dark:text-blue-200">{mission.leg==='hospital'?'Trajet vers l’hôpital':'Trajet vers l’incident'} : {mission.routeMeta?.name||'calcul en cours'}</div><div className="mt-1 text-xs text-blue-700/70 dark:text-blue-300/70">ETA opérationnelle <b>{telemetry?.operationalEta||mission.routeMeta?.eta||'—'} min</b> · reste {telemetry?.distanceRemaining||0} km · {telemetry?.speed||0} km/h</div></div>
      {hospital&&<div className="rounded-2xl border-2 border-emerald-300 bg-gradient-to-br from-emerald-700 to-emerald-500 px-4 py-3 text-white shadow-lg shadow-emerald-900/15"><div className="text-[9px] font-black uppercase tracking-wider text-emerald-50">✓ Hôpital recommandé · H · score {mission.hospitalDecision?.decisionScore||hospital.decisionScore||'—'}%</div><div className="mt-1 text-sm font-bold">{hospital.name}</div><div className="mt-1 text-[11px] text-emerald-50">Incident → hôpital · ETA <b>{mission.hospitalRouteMeta?.eta||hospital.decisionEta||hospital.eta} min</b> · {mission.hospitalRouteMeta?.distance||hospital.distance||'—'} km · {hospital.beds} places</div></div>}
      <div className="flex gap-2"><button type="button" className="btn-secondary" onClick={()=>onNavigate('interventions')}>Suivre</button><button type="button" className="btn-secondary text-red-600" onClick={onReset} aria-label="Réinitialiser la mission"><RotateCcw size={15}/></button></div>
    </div>
    <div className="mt-3 h-2 overflow-hidden rounded-full bg-blue-100 dark:bg-blue-950"><div className="h-full rounded-full bg-blue-600 transition-all duration-500" style={{width:`${telemetry?.progress||0}%`}}/></div>
    <div className="lotisec-scroll-panel mt-3 flex gap-2 overflow-x-auto pb-1">{missionSteps.map((step,index)=><div key={step} className={`min-w-[132px] flex-1 rounded-xl border px-3 py-2 ${index===currentIndex?'border-blue-500 bg-blue-50 text-blue-800 dark:bg-blue-950/30 dark:text-blue-200':index<currentIndex?'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300':'border-slate-200 text-slate-400 dark:border-slate-700'}`}><div className="text-[8px] font-black uppercase tracking-wider">{index<currentIndex?'✓ Validée':index===currentIndex?'En cours':`Étape ${index+1}`}</div><div className="mt-1 text-[10px] font-semibold">{step}</div></div>)}</div>
    </div>
  </section>
}

function MissionSummary({mission,hospital,alert,onNavigate}){
  const totalDistance=Number(mission.ambulanceRouteMeta?.distance||0)+Number(mission.hospitalRouteMeta?.distance||0)
  const totalEta=Number(mission.ambulanceRouteMeta?.eta||0)+Number(mission.hospitalRouteMeta?.eta||0)
  return <section className="surface mb-4 overflow-hidden border-emerald-300"><div className="bg-gradient-to-r from-emerald-800 to-emerald-500 p-4 text-white"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><CheckCircle2 size={23}/></span><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-100">Résumé final disponible</div><h3 className="mt-1 text-lg font-bold">Mission terminée et prise en charge confirmée</h3></div></div></div><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><FinalStat label="Incident" value={alert?.id}/><FinalStat label="Ambulance" value={mission.ambulanceId}/><FinalStat label="Hôpital" value={hospital?.name||'—'}/><FinalStat label="Distance totale" value={`${totalDistance.toFixed(1)} km`}/><FinalStat label="ETA cumulée" value={`${totalEta} min`}/></div><div className="flex flex-col justify-between gap-3 border-t border-slate-100 p-4 md:flex-row md:items-center dark:border-slate-800"><p className="text-xs muted">{mission.rerouteCount||0} reroutage(s) · {alert?.victims||0} victime(s) · données de mission prêtes pour le rapport Excel.</p><button type="button" className="btn-primary" onClick={()=>onNavigate('statistics')}>Ouvrir le rapport</button></div></section>
}

function FinalStat({label,value}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-[9px] font-bold uppercase tracking-wider muted">{label}</span><b className="mt-1 block truncate text-sm">{value||'—'}</b></div>}
