import { Eye, EyeOff, KeyRound, LockKeyhole, ScrollText, ShieldCheck, UserCog, Users } from 'lucide-react'
import { Kpi, PageTitle, Status } from '../components/UI'

const permissions=[
  ['Consulter les opérations',true,true,true],
  ['Valider un signalement',true,true,false],
  ['Affecter une ambulance',true,true,false],
  ['Confirmer un hôpital',true,true,false],
  ['Modifier les capacités',true,false,false],
  ['Gérer les rôles',true,false,false],
  ['Exporter les journaux',true,true,false],
]

export default function Security({operator,securityConfig,onUpdateSecurity,onChangeRole,auditLog,onNavigate,dataMode}){
  const operatorEvents=auditLog.filter(item=>item.operatorId===operator.id||item.actor===operator.name||String(item.actor).includes('Admin')).length
  return <>
    <PageTitle title="Sécurité & accès" subtitle="Rôles, confidentialité, validation humaine et traçabilité des actions sensibles." action={<Status tone="green"><ShieldCheck size={14}/>POLITIQUES ACTIVES</Status>}/>
    <section className="surface mb-4 overflow-hidden"><div className="bg-gradient-to-r from-[#073b67] to-blue-600 p-5 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><UserCog size={23}/></span><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-blue-100">Session opérateur</div><h3 className="mt-1 text-xl font-bold">{operator.name}</h3><p className="mt-1 text-xs text-blue-100">Identifiant {operator.id} · rôle {operator.role} · environnement {dataMode==='test'?'test isolé':'opérationnel réel'}</p></div></div><div className="flex flex-wrap gap-2"><select aria-label="Rôle de la session" value={operator.role} onChange={event=>onChangeRole(event.target.value)} className="rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-sm font-semibold text-white outline-none"><option className="text-slate-900">Administrateur</option><option className="text-slate-900">Opérateur</option><option className="text-slate-900">Observateur</option></select><Status tone="green">SESSION ACTIVE</Status></div></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Rôles définis" value="3" icon={Users} tone="blue" hint="Administrateur · Opérateur · Observateur"/><Kpi label="Validations obligatoires" value={securityConfig.requireHumanValidation?'Actives':'Inactives'} icon={LockKeyhole} tone={securityConfig.requireHumanValidation?'green':'red'} hint="Affectation et orientation"/><Kpi label="Anonymisation" value={securityConfig.anonymizeVictims?'Active':'Inactive'} icon={securityConfig.anonymizeVictims?EyeOff:Eye} tone={securityConfig.anonymizeVictims?'violet':'amber'} hint="Identité et contact des victimes"/><Kpi label="Actions de la session" value={operatorEvents} icon={ScrollText} tone="amber" hint="Horodatées dans le journal"/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><section className="surface p-4"><h3 className="font-semibold">Politiques de confidentialité</h3><p className="mt-1 text-xs muted">Les réglages sensibles restent imposés en environnement réel.</p><div className="mt-4 space-y-3"><Policy title="Validation humaine avant décision" detail="Aucune affectation ou orientation n’est exécutée sans confirmation attribuée." checked={securityConfig.requireHumanValidation} locked/><Policy title="Anonymiser les victimes" detail="Les noms, numéros et pièces jointes ne sont ni affichés ni exportés." checked={securityConfig.anonymizeVictims} onChange={()=>onUpdateSecurity('anonymizeVictims',!securityConfig.anonymizeVictims)}/><Policy title="Journal d’audit inviolable" detail="Les actions sont horodatées avec l’opérateur, le rôle et la référence métier." checked={securityConfig.auditEnabled} locked/><Policy title="Séparer le réel du mode test" detail="Les flux terrain sont mis en attente tant que le bac à sable est actif." checked={securityConfig.isolateTestData} locked/></div><button type="button" onClick={()=>onNavigate('audit')} className="btn-secondary mt-4 w-full">Consulter le journal complet</button></section><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Matrice des autorisations</h3><p className="mt-1 text-xs muted">Contrôle d’accès par rôle prévu pour Keycloak et appliqué dans le prototype.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr><th className="p-3">Action</th><th>Administrateur</th><th>Opérateur</th><th>Observateur</th></tr></thead><tbody>{permissions.map(row=><tr key={row[0]} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold">{row[0]}</td>{row.slice(1).map((allowed,index)=><td key={index}>{allowed?<span className="inline-flex items-center gap-1 text-emerald-600"><ShieldCheck size={14}/>Autorisé</span>:<span className="inline-flex items-center gap-1 text-slate-400"><KeyRound size={14}/>Refusé</span>}</td>)}</tr>)}</tbody></table></div><div className="border-t border-blue-100 bg-blue-50 p-4 text-xs leading-5 text-blue-800 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200"><b>Connexion réelle :</b> le rôle devra provenir des claims du jeton Keycloak transmis par le backend. Aucun secret administrateur n’est stocké dans le navigateur.</div></section></div>
  </>
}

function Policy({title,detail,checked,onChange,locked}){return <button type="button" onClick={locked?undefined:onChange} className={`flex w-full items-start gap-3 rounded-xl border p-3 text-left ${checked?'border-emerald-200 bg-emerald-50/60 dark:border-emerald-900 dark:bg-emerald-950/20':'border-slate-200 dark:border-slate-700'} ${locked?'cursor-default':'hover:border-blue-300'}`}><span className={`mt-0.5 h-5 w-9 shrink-0 rounded-full p-0.5 transition ${checked?'bg-emerald-600':'bg-slate-300'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${checked?'translate-x-4':''}`}/></span><span><b className="block text-sm">{title}</b><span className="mt-1 block text-xs leading-5 muted">{detail}{locked?' · Politique verrouillée.':''}</span></span></button>}
