import { Activity, CheckCircle2, CloudCog, Database, Gauge, Map, Radio, RefreshCw, Server, ShieldCheck, Smartphone, WifiOff } from 'lucide-react'
import { Kpi, PageTitle, Status } from '../components/UI'

const iconMap={mobile:Smartphone,realtime:Radio,api:Server,database:Database,routing:Map,fog:CloudCog,audit:ShieldCheck}
const toneFor=status=>status==='operational'?'green':status==='degraded'?'amber':status==='offline'?'red':'blue'
const labelFor=status=>status==='operational'?'OPÉRATIONNEL':status==='degraded'?'DÉGRADÉ':status==='offline'?'INDISPONIBLE':'PRÊT À CONFIGURER'

export default function SystemHealth({health,mobileFeedStatus,dataMode,realQueueCount,fog,onRefresh,onNavigate}){
  const services=health?.services||[]
  const operational=services.filter(item=>item.status==='operational').length
  const degraded=services.filter(item=>item.status==='degraded').length
  const latency=health?.backendLatency
  return <>
    <PageTitle title="État du système" subtitle="Supervision de la chaîne Mobile–Web–Fog–Cloud et des composants géodécisionnels." action={<button type="button" onClick={onRefresh} disabled={health?.checking} className="btn-primary"><RefreshCw size={16} className={health?.checking?'animate-spin':''}/>{health?.checking?'Vérification…':'Vérifier maintenant'}</button>}/>
    <section className={`surface mb-4 overflow-hidden border-2 ${degraded?'border-amber-300 dark:border-amber-800':'border-emerald-300 dark:border-emerald-800'}`}><div className={`${degraded?'bg-amber-500':'bg-emerald-600'} p-4 text-white`}><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><Activity size={23}/></span><div><div className="text-[10px] font-black uppercase tracking-[.18em] opacity-80">Supervision LOTISEC</div><h3 className="mt-1 text-xl font-bold">{degraded?'Continuité assurée avec réserves':'Chaîne opérationnelle prête'}</h3><p className="mt-1 text-xs opacity-85">Dernière vérification : {health?.lastCheckedAt||'non exécutée'} · données {dataMode==='test'?'du bac à sable test':'du flux mobile réel'}</p></div></div><Status tone={degraded?'amber':'green'}>{operational}/{services.length} SERVICES ACTIFS</Status></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Services opérationnels" value={`${operational}/${services.length}`} icon={CheckCircle2} tone="green" hint={`${degraded} service(s) dégradé(s)`}/><Kpi label="Latence backend" value={latency==null?'—':`${latency} ms`} icon={Gauge} tone="blue" hint={health?.backendVersion?`Version ${health.backendVersion}`:'Mesurée via /health'}/><Kpi label="File Fog locale" value={fog?.queue?.length||0} icon={CloudCog} tone={fog?.effectiveMode==='offline'?'red':'violet'} hint={`${fog?.stats?.syncRate||0}% d’acquittements`}/><Kpi label="Événements réels isolés" value={realQueueCount||0} icon={Smartphone} tone="amber" hint={dataMode==='test'?'Conservés hors du mode test':'Flux réel actif'}/></div>
    <section className="surface mt-4 overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><h3 className="font-semibold">Composants supervisés</h3><p className="mt-1 text-xs muted">Les états distinguent une connexion réellement vérifiée d’un adaptateur seulement prêt à être configuré.</p></div><div className="grid gap-3 p-4 lg:grid-cols-2">{services.map(service=>{const Icon=iconMap[service.id]||Server;return <article key={service.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${toneFor(service.status)==='green'?'bg-emerald-100 text-emerald-700':toneFor(service.status)==='amber'?'bg-amber-100 text-amber-700':toneFor(service.status)==='red'?'bg-red-100 text-red-700':'bg-blue-100 text-blue-700'}`}><Icon size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><b>{service.name}</b><Status tone={toneFor(service.status)}>{labelFor(service.status)}</Status></div><p className="mt-1 text-xs leading-5 muted">{service.detail}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[10px] muted"><span>Dernier signal : <b className="text-slate-700 dark:text-slate-200">{service.lastSignal||'—'}</b></span>{service.latency!=null&&<span>Latence : <b className="text-slate-700 dark:text-slate-200">{service.latency} ms</b></span>}</div></div></div></article>})}</div></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="surface p-4"><div className="flex items-center gap-2"><Radio size={18} className={mobileFeedStatus==='connected'?'animate-pulse text-emerald-600':'text-blue-600'}/><h3 className="font-semibold">Canal mobile réel</h3></div><p className="mt-2 text-sm leading-6 muted">La connexion réelle reste indépendante du bac à sable. En mode test, les événements terrain sont placés en attente et ne modifient ni la carte, ni les statistiques, ni le scénario.</p><button type="button" onClick={()=>onNavigate('settings')} className="btn-secondary mt-4 w-full">Ouvrir la configuration mobile</button></section><section className="surface p-4"><div className="flex items-center gap-2"><WifiOff size={18} className="text-amber-600"/><h3 className="font-semibold">Continuité Fog</h3></div><p className="mt-2 text-sm leading-6 muted">En cas de connexion dégradée ou interrompue, les événements restent dans la file locale puis sont synchronisés lors du rétablissement du Cloud.</p><button type="button" onClick={()=>onNavigate('fog')} className="btn-secondary mt-4 w-full">Voir la synchronisation Fog–Cloud</button></section></div>
  </>
}
