import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../api/config';import {colors} from '../theme/colors';import {fonts,fontSizes} from '../theme/typography';

const keys=[['first_name','Prénom'],['last_name','Nom'],['birth_date','Date de naissance'],['gender','Sexe'],['nationality','Nationalité'],['blood_type','Groupe sanguin'],['height','Taille (cm)'],['weight','Poids (kg)'],['allergies','Allergies'],['conditions','Maladies chroniques'],['medications','Traitements'],['disabilities','Handicap / besoins'],['doctor_name','Médecin traitant'],['doctor_phone','Téléphone médecin']] as const;
export default function CitizenProfileScreen(){const[form,setForm]=useState<any>(null);const[contacts,setContacts]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[pin,setPin]=useState('');const[confirmation,setConfirmation]=useState('');const[deletePassword,setDeletePassword]=useState('');
  const load=()=>api('/profil/me').then(data=>{setForm(data.profile);setContacts(data.emergency_contacts||[]);}).catch((e:any)=>Alert.alert('Erreur',e.message)).finally(()=>setLoading(false));useEffect(()=>{void load();},[]);
  const save=async()=>{setSaving(true);try{await api('/profil','POST',{profile_type:form.profile_type||'adult',first_name:form.first_name,last_name:form.last_name,birth_date:form.birth_date||'',gender:form.gender||'',nationality:form.nationality||'Togo',document_type:form.document_type||'Non renseigné',document_number:form.document_number||'0000',blood_type:form.blood_type||'NC',height:form.height?Number(form.height):null,weight:form.weight?Number(form.weight):null,allergies:form.allergies||'',conditions:form.conditions||'',medications:form.medications||'',surgeries:form.surgeries||'',disabilities:form.disabilities||'',doctor_name:form.doctor_name||'',doctor_phone:form.doctor_phone||'',has_vehicle:Boolean(form.has_vehicle),vehicle_type:form.vehicle_type||'',plate:form.plate||'',brand:form.brand||'',model:form.model||'',emergency_contacts:contacts.filter(c=>c.name&&c.phone)});Alert.alert('Enregistré','Votre fiche médicale est à jour.');}catch(e:any){Alert.alert('Erreur',e.message);}finally{setSaving(false);}};
  const updatePin=async()=>{if(!/^\d{4,6}$/.test(pin))return Alert.alert('PIN invalide','Utilisez 4 à 6 chiffres.');if(pin!==confirmation)return Alert.alert('Confirmation incorrecte','Les deux PIN ne correspondent pas.');try{await api('/profil/pin','PUT',{pin});setPin('');setConfirmation('');Alert.alert('PIN mis à jour','Votre nouveau PIN personnel est actif.');}catch(e:any){Alert.alert('Erreur',e.message);}};
  const clearMedicalData=()=>{if(!deletePassword)return Alert.alert('Mot de passe requis','Confirmez avec le mot de passe du compte.');Alert.alert('Effacer la fiche médicale ?','Cette action supprime les constantes, contacts, véhicule et PIN.',[{text:'Annuler',style:'cancel'},{text:'Effacer',style:'destructive',onPress:async()=>{try{await api('/profil/medical-data','DELETE',{password:deletePassword});setDeletePassword('');setLoading(true);await load();Alert.alert('Données effacées','Votre compte et votre QR restent actifs avec une fiche vide.');}catch(e:any){Alert.alert('Erreur',e.message);}}}]);};
  if(loading||!form)return <SafeAreaView style={s.center}><ActivityIndicator color={colors.primary}/></SafeAreaView>;
  return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Ionicons name="shield-checkmark-outline" size={32} color={colors.primary}/><View><Text style={s.title}>Mon profil médical</Text><Text style={s.sub}>Visible uniquement après autorisation</Text></View></View><View style={s.card}><Text style={s.section}>Identité et informations vitales</Text>{keys.map(([key,label])=><View key={key} style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={String(form[key]??'')} keyboardType={key==='height'||key==='weight'?'numeric':'default'} onChangeText={value=>setForm({...form,[key]:value})}/></View>)}<Text style={s.section}>Contact d'urgence</Text><View style={s.field}><Text style={s.label}>Nom</Text><TextInput style={s.input} value={contacts[0]?.name||''} onChangeText={value=>setContacts([{...(contacts[0]||{}),name:value,relation:contacts[0]?.relation||'Proche'}])}/></View><View style={s.field}><Text style={s.label}>Téléphone</Text><TextInput style={s.input} value={contacts[0]?.phone||''} keyboardType="phone-pad" onChangeText={value=>setContacts([{...(contacts[0]||{}),phone:value,relation:contacts[0]?.relation||'Proche'}])}/></View><TouchableOpacity style={s.primary} disabled={saving} onPress={save}><Text style={s.primaryText}>{saving?'Enregistrement…':'Enregistrer ma fiche'}</Text></TouchableOpacity></View><View style={s.card}><Text style={s.section}>PIN personnel de secours</Text><Text style={s.help}>Le PIN n'est jamais contenu dans votre QR. Communiquez-le seulement en cas de besoin.</Text><TextInput style={s.input} value={pin} onChangeText={v=>setPin(v.replace(/\D/g,'').slice(0,6))} placeholder="Nouveau PIN" placeholderTextColor={colors.textLight} secureTextEntry keyboardType="number-pad"/><TextInput style={s.input} value={confirmation} onChangeText={v=>setConfirmation(v.replace(/\D/g,'').slice(0,6))} placeholder="Confirmer le PIN" placeholderTextColor={colors.textLight} secureTextEntry keyboardType="number-pad"/><TouchableOpacity style={s.secondary} onPress={updatePin}><Text style={s.secondaryText}>Définir ou renouveler le PIN</Text></TouchableOpacity></View><View style={[s.card,s.dangerCard]}><Text style={s.section}>Effacer ma fiche médicale</Text><Text style={s.help}>Le compte et le QR resteront actifs, mais les données médicales, contacts et PIN seront supprimés.</Text><TextInput style={s.input} value={deletePassword} onChangeText={setDeletePassword} placeholder="Mot de passe du compte" placeholderTextColor={colors.textLight} secureTextEntry/><TouchableOpacity style={s.danger} onPress={clearMedicalData}><Text style={s.primaryText}>Effacer mes données médicales</Text></TouchableOpacity></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},content:{padding:16,paddingBottom:110,gap:14},header:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:colors.primaryDark,marginHorizontal:-16,marginTop:-16,paddingHorizontal:20,paddingVertical:24,borderBottomLeftRadius:22,borderBottomRightRadius:22},title:{fontFamily:fonts.bold,fontSize:fontSizes.xl,color:colors.white},sub:{fontFamily:fonts.regular,fontSize:fontSizes.sm,color:'#C4D2E0'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:16,gap:10},dangerCard:{borderColor:colors.danger},section:{fontFamily:fonts.bold,fontSize:fontSizes.md,color:colors.text,marginBottom:4},field:{gap:5},label:{fontFamily:fonts.medium,fontSize:fontSizes.xs,color:colors.textSecondary},input:{minHeight:48,borderWidth:1,borderColor:colors.borderStrong,borderRadius:12,paddingHorizontal:13,color:colors.text,backgroundColor:colors.surfaceRaised},help:{fontFamily:fonts.regular,fontSize:fontSizes.xs,lineHeight:18,color:colors.textSecondary},primary:{backgroundColor:colors.primary,padding:15,borderRadius:12,alignItems:'center',marginTop:6},primaryText:{color:colors.white,fontFamily:fonts.bold},secondary:{borderWidth:1,borderColor:colors.primary,padding:14,borderRadius:12,alignItems:'center'},secondaryText:{color:colors.primary,fontFamily:fonts.bold},danger:{backgroundColor:colors.danger,padding:14,borderRadius:12,alignItems:'center'}});
