import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import * as Location from 'expo-location';
import MapView,{Marker} from '../components/PlatformMap';
import {api} from '../api/config';
import {hydrateSession} from '../services/session';
import {colors} from '../theme/colors';

const nextAction:Record<string,{status:string;label:string}>={assigned:{status:'accepted',label:'Accepter la mission'},accepted:{status:'en_route',label:'Départ vers le lieu'},en_route:{status:'on_scene',label:'Arrivé sur les lieux'},on_scene:{status:'patient_loaded',label:'Patient pris en charge'}};
const statusLabel:Record<string,string>={assigned:'Nouvelle affectation',accepted:'Mission acceptée',en_route:'En route',on_scene:'Sur les lieux',patient_loaded:'Patient pris en charge',hospital_requested:'Admission demandée',to_hospital:"Transport vers l'hôpital",arrived_hospital:"Arrivé à l'hôpital",completed:'Terminée'};

export default function OperationalMissionsScreen(){
  const [missions,setMissions]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const result=await api('/api/v1/interventions');const items=result.interventions||[];setMissions(items);setSelected((current:any)=>items.find((item:any)=>item.id===current?.id)||items[0]||null);setError('');}catch(e:any){setError(e.message||'Missions indisponibles');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[load]);
  useEffect(()=>{let subscription:Location.LocationSubscription|undefined;(async()=>{if(!selected?.response_unit_id)return;const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')return;subscription=await Location.watchPositionAsync({accuracy:Location.Accuracy.Balanced,timeInterval:8000,distanceInterval:20},async location=>{try{await api(`/api/v1/resources/${selected.response_unit_id}/location`,'PATCH',{latitude:location.coords.latitude,longitude:location.coords.longitude});}catch{}});})();return()=>subscription?.remove();},[selected?.response_unit_id]);
  const advance=async()=>{const action=nextAction[selected?.status];if(!action)return;setBusy(true);try{await api(`/api/v1/interventions/${selected.id}/status`,'PATCH',{status:action.status});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  if(loading)return <SafeAreaView style={styles.center}><ActivityIndicator color={colors.primary}/><Text>Chargement des missions…</Text></SafeAreaView>;
  const incident=selected?.incident;const action=nextAction[selected?.status];
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.eyebrow}>ESPACE TERRAIN SÉCURISÉ</Text><Text style={styles.title}>Mes interventions</Text></View><TouchableOpacity style={styles.refresh} onPress={load}><Ionicons name="refresh" size={21} color={colors.primary}/></TouchableOpacity></View>{error?<Text style={styles.error}>{error}</Text>:null}{!selected?<View style={styles.empty}><Ionicons name="shield-checkmark-outline" size={52} color={colors.textLight}/><Text style={styles.emptyTitle}>Aucune mission affectée</Text><Text style={styles.muted}>Les missions de votre organisation apparaîtront ici automatiquement.</Text></View>:<ScrollView contentContainerStyle={styles.content}><View style={styles.status}><View style={styles.dot}/><Text style={styles.statusText}>{statusLabel[selected.status]||selected.status}</Text></View>{incident?.latitude&&incident?.longitude?<View style={styles.mapWrap}><MapView style={styles.map} initialRegion={{latitude:Number(incident.latitude),longitude:Number(incident.longitude),latitudeDelta:.035,longitudeDelta:.035}} showsUserLocation><Marker coordinate={{latitude:Number(incident.latitude),longitude:Number(incident.longitude)}} title="Lieu de l'incident"/></MapView></View>:null}<View style={styles.card}><Text style={styles.cardTitle}>{incident?.type||'Intervention'}</Text><Text style={styles.address}>{incident?.address||'Position GPS disponible'}</Text><View style={styles.facts}><View><Text style={styles.factLabel}>GRAVITÉ</Text><Text style={styles.factValue}>{incident?.severity||'NC'}</Text></View><View><Text style={styles.factLabel}>VICTIMES</Text><Text style={styles.factValue}>{incident?.victims??0}</Text></View><View><Text style={styles.factLabel}>PRIORITÉ</Text><Text style={styles.factValue}>{incident?.priority_score??'—'}/100</Text></View></View></View>{action?<TouchableOpacity disabled={busy} style={styles.primary} onPress={advance}>{busy?<ActivityIndicator color="#fff"/>:<><Ionicons name="navigate" size={20} color="#fff"/><Text style={styles.primaryText}>{action.label}</Text></>}</TouchableOpacity>:null}<Text style={styles.notice}>Votre position est partagée uniquement pendant une mission active afin d'alimenter le suivi de la supervision.</Text><Text style={styles.section}>FILE DE MON ORGANISATION</Text>{missions.map(item=><TouchableOpacity key={item.id} style={[styles.mission,item.id===selected.id&&styles.missionActive]} onPress={()=>setSelected(item)}><View style={{flex:1}}><Text style={styles.missionTitle}>{item.incident?.type||item.id}</Text><Text style={styles.muted}>{statusLabel[item.status]||item.status}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.textLight}/></TouchableOpacity>)}</ScrollView>}</SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},header:{padding:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.white,borderBottomWidth:1,borderColor:colors.border},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.1,color:colors.primary},title:{fontSize:25,fontWeight:'800',color:colors.text,marginTop:4},refresh:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:colors.primaryLight},content:{padding:16,paddingBottom:100},error:{color:colors.danger,padding:10,textAlign:'center'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:35},emptyTitle:{fontSize:18,fontWeight:'800',color:colors.text,marginTop:12},muted:{fontSize:12,color:colors.textSecondary,marginTop:4,lineHeight:18},status:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:12},dot:{width:9,height:9,borderRadius:5,backgroundColor:colors.success},statusText:{fontWeight:'800',color:colors.text},mapWrap:{height:280,borderRadius:18,overflow:'hidden',borderWidth:1,borderColor:colors.border},map:{flex:1},card:{padding:17,borderRadius:17,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,marginTop:12},cardTitle:{fontSize:19,fontWeight:'800',color:colors.text},address:{color:colors.textSecondary,marginTop:5},facts:{flexDirection:'row',justifyContent:'space-between',marginTop:18,paddingTop:14,borderTopWidth:1,borderColor:colors.border},factLabel:{fontSize:9,fontWeight:'800',color:colors.textLight},factValue:{fontSize:16,fontWeight:'800',color:colors.text,marginTop:4},primary:{minHeight:54,borderRadius:15,backgroundColor:colors.primary,flexDirection:'row',gap:9,alignItems:'center',justifyContent:'center',marginTop:13},primaryText:{color:'#fff',fontWeight:'800'},notice:{fontSize:11,lineHeight:17,color:colors.textSecondary,margin:13},section:{fontSize:11,fontWeight:'800',letterSpacing:1,color:colors.textSecondary,marginTop:10,marginBottom:8},mission:{flexDirection:'row',alignItems:'center',padding:14,borderRadius:14,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,marginBottom:8},missionActive:{borderColor:colors.primary,borderWidth:2},missionTitle:{fontWeight:'800',color:colors.text}});
