import React,{useEffect,useState} from 'react';
import {StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {clearSession,hydrateSession} from '../services/session';
import {colors} from '../theme/colors';

export default function ProfessionalAccountScreen({navigation}:any){const [user,setUser]=useState<any>(null);useEffect(()=>{hydrateSession().then(session=>setUser(session?.user));},[]);const logout=async()=>{await clearSession();navigation.getParent()?.reset({index:0,routes:[{name:'Landing'}]});};return <SafeAreaView style={styles.safe}><View style={styles.header}><Ionicons name="shield-checkmark" size={34} color={colors.primary}/><Text style={styles.title}>Compte institutionnel</Text><Text style={styles.subtitle}>Accès adapté à votre rôle et à votre organisation</Text></View><View style={styles.card}><Text style={styles.label}>OPÉRATEUR</Text><Text style={styles.value}>{[user?.first_name,user?.last_name].filter(Boolean).join(' ')||user?.phone||'—'}</Text><Text style={styles.label}>RÔLES</Text><Text style={styles.value}>{(user?.roles||[]).join(' · ')||'—'}</Text><Text style={styles.label}>ORGANISATION</Text><Text style={styles.value}>{user?.organization?.name||user?.organizations?.[0]?.name||'—'}</Text></View><View style={styles.notice}><Ionicons name="lock-closed-outline" size={20} color={colors.primary}/><Text style={styles.noticeText}>Les missions, ressources et actions visibles sont filtrées par le backend selon votre compte.</Text></View><TouchableOpacity style={styles.logout} onPress={logout}><Ionicons name="log-out-outline" size={21} color="#fff"/><Text style={styles.logoutText}>Se déconnecter</Text></TouchableOpacity></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background,padding:20},header:{alignItems:'center',paddingVertical:30},title:{fontSize:24,fontWeight:'800',color:colors.text,marginTop:12},subtitle:{fontSize:12,color:colors.textSecondary,textAlign:'center',marginTop:6},card:{padding:20,borderRadius:18,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border},label:{fontSize:10,fontWeight:'800',letterSpacing:1,color:colors.textLight,marginTop:14},value:{fontSize:16,fontWeight:'700',color:colors.text,marginTop:5},notice:{flexDirection:'row',gap:10,padding:15,borderRadius:14,backgroundColor:colors.primaryLight,marginTop:15},noticeText:{flex:1,fontSize:12,lineHeight:18,color:colors.textSecondary},logout:{minHeight:54,borderRadius:15,backgroundColor:colors.danger,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginTop:20},logoutText:{color:'#fff',fontWeight:'800'}});
