import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,FlatList,KeyboardAvoidingView,Platform,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../api/config';
import {supabase} from '../api/supabase';
import {hydrateSession} from '../services/session';
import {colors} from '../theme/colors';

export default function RideChatScreen({route,navigation}:any){
  const {rideId}=route.params;const [messages,setMessages]=useState<any[]>([]);const [text,setText]=useState('');const [userId,setUserId]=useState('');const [error,setError]=useState('');const [hasMore,setHasMore]=useState(false);const [loadingOlder,setLoadingOlder]=useState(false);const [chatOpen,setChatOpen]=useState(true);const list=useRef<FlatList>(null);
  const load=async()=>{try{const s=await hydrateSession();if(!s)return;setUserId(s.user.id);const data=await api(`/zem/rides/${rideId}/messages`,'GET',undefined,s.token);setMessages(data.messages||[]);setHasMore(Boolean(data.has_more));setChatOpen(Boolean(data.chat_open));await api(`/zem/rides/${rideId}/messages/read`,'PATCH',{},s.token);}catch(e:any){setError(e.message);}};
  const loadOlder=async()=>{const first=messages[0];if(!first||loadingOlder)return;setLoadingOlder(true);try{const s=await hydrateSession();if(!s)return;const data=await api(`/zem/rides/${rideId}/messages?before=${encodeURIComponent(first.created_at)}`,'GET',undefined,s.token);setMessages(prev=>[...(data.messages||[]),...prev]);setHasMore(Boolean(data.has_more));}catch(e:any){setError(e.message);}finally{setLoadingOlder(false);}};
  useEffect(()=>{load();const realtime=supabase;if(!realtime)return;const channel=realtime.channel(`ride-chat-${rideId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_messages',filter:`ride_id=eq.${rideId}`},({new:item})=>setMessages(prev=>prev.some(m=>m.id===item.id)?prev:[...prev,item])).subscribe();return()=>{realtime.removeChannel(channel);};},[rideId]);
  const uuid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
  const send=async()=>{const body=text.trim();if(!body||!chatOpen)return;setText('');const now=Date.now();const clientMessageId=uuid();const temp={id:`temp-${now}`,sender_id:userId,body,created_at:new Date().toISOString()};setMessages(prev=>[...prev,temp]);try{const s=await hydrateSession();const result=await api(`/zem/rides/${rideId}/messages`,'POST',{body,client_message_id:clientMessageId},s?.token);setMessages(prev=>prev.map(m=>m.id===temp.id?result.message:m));}catch(e:any){setMessages(prev=>prev.filter(m=>m.id!==temp.id));setError(e.message);}};
  return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.icon}><Ionicons name="arrow-back" size={22} color={colors.text}/></TouchableOpacity><Text style={styles.title}>Discussion de course</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}<FlatList ref={list} data={messages} keyExtractor={m=>m.id} contentContainerStyle={styles.list} ListHeaderComponent={hasMore?<TouchableOpacity style={styles.older} onPress={loadOlder}>{loadingOlder?<ActivityIndicator size="small" color={colors.primary}/>:<Text style={styles.olderText}>Afficher les messages précédents</Text>}</TouchableOpacity>:null} onContentSizeChange={()=>list.current?.scrollToEnd({animated:true})} renderItem={({item})=><View style={[styles.bubble,item.sender_id===userId?styles.mine:styles.theirs]}><Text style={item.sender_id===userId?styles.mineText:styles.theirText}>{item.body}</Text><View style={styles.messageMeta}><Text style={styles.time}>{new Date(item.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Text>{item.sender_id===userId?<Ionicons name={item.read_at?'checkmark-done':'checkmark'} size={13} color={item.read_at?colors.success:colors.textLight}/>:null}</View></View>}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}>{chatOpen?<View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Écrire un message" style={styles.input} multiline/><TouchableOpacity onPress={send} style={styles.send} accessibilityLabel="Envoyer"><Ionicons name="send" size={20} color={colors.white}/></TouchableOpacity></View>:<View style={styles.closed}><Ionicons name="lock-closed-outline" size={17} color={colors.textSecondary}/><Text style={styles.closedText}>Course clôturée · conversation en lecture seule</Text></View>}</KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:60,flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:12,backgroundColor:colors.white,borderBottomWidth:1,borderColor:colors.border},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:17,fontWeight:'700',color:colors.text},error:{color:colors.danger,padding:10,textAlign:'center'},list:{padding:16,gap:8},older:{alignSelf:'center',padding:10},olderText:{color:colors.primary,fontWeight:'700',fontSize:12},bubble:{maxWidth:'82%',padding:12,borderRadius:16},mine:{alignSelf:'flex-end',backgroundColor:colors.primary},theirs:{alignSelf:'flex-start',backgroundColor:colors.white,borderWidth:1,borderColor:colors.border},mineText:{color:colors.white},theirText:{color:colors.text},messageMeta:{flexDirection:'row',alignItems:'center',alignSelf:'flex-end',gap:3,marginTop:4},time:{fontSize:9,color:colors.textLight},composer:{flexDirection:'row',padding:12,gap:8,backgroundColor:colors.white,borderTopWidth:1,borderColor:colors.border},input:{flex:1,minHeight:46,maxHeight:110,backgroundColor:colors.surfaceRaised,borderRadius:16,paddingHorizontal:14,paddingVertical:12,color:colors.text},send:{width:46,height:46,borderRadius:16,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},closed:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,backgroundColor:colors.white,borderTopWidth:1,borderColor:colors.border},closedText:{color:colors.textSecondary,fontSize:12}});
