import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../api/config';import {supabase} from '../api/supabase';import {hydrateSession} from '../services/session';import {colors} from '../theme/colors';
const activeStatuses=['searching','offered','accepted','driver_en_route','driver_arrived','ready_to_start','in_progress','driver_completed'];
const labels:Record<string,string>={searching:'Recherche en cours',offered:'Proposition envoyée',accepted:'Zem affecté',driver_en_route:'Le Zem arrive',driver_arrived:'Zem arrivé',ready_to_start:'Prêt à partir',in_progress:'Vers la destination',driver_completed:'Fin à confirmer',completed:'Terminée',canceled:'Annulée',expired:'Expirée',no_show:'Absence signalée',disputed:'Contestée'};
export default function RidesScreen({navigation}:any){const [rides,setRides]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{try{const s=await hydrateSession();if(!s)return;const result=await api('/zem/history?page=1&page_size=50','GET',undefined,s.token);setRides(result.rides||[]);}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{load();const realtime=supabase;if(!realtime)return;let channel:any;(async()=>{const s=await hydrateSession();if(!s)return;channel=realtime.channel(`my-rides-${s.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'rides'},load).subscribe();})();return()=>{if(channel)realtime.removeChannel(channel);};},[load]);
  const active=rides.find(r=>activeStatuses.includes(r.status));const history=rides.filter(r=>r.id!==active?.id);
  const card=(ride:any,primary=false)=><TouchableOpacity key={ride.id} accessibilityRole="button" style={[styles.card,primary&&styles.active]} onPress={()=>navigation.navigate('RideDetail',{rideId:ride.id})}><View style={[styles.icon,{backgroundColor:primary?colors.primary:ride.status==='completed'?colors.success:colors.surfaceRaised}]}><Ionicons name={primary?'navigate-outline':ride.status==='completed'?'checkmark':'time-outline'} size={22} color={primary||ride.status==='completed'?colors.white:colors.textSecondary}/></View><View style={styles.grow}><View style={styles.titleRow}><Text style={styles.cardTitle}>{labels[ride.status]||ride.status}</Text>{Number(ride.unread_messages)>0?<View style={styles.unread}><Text style={styles.unreadText}>{ride.unread_messages}</Text></View>:null}</View><Text style={styles.meta}>{new Date(ride.created_at).toLocaleDateString()} · {ride.distance_km} km</Text></View><View><Text style={styles.price}>{ride.price_fcfa} FCFA</Text><Ionicons name="chevron-forward" size={18} color={colors.textLight} style={styles.chevron}/></View></TouchableOpacity>;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>Mes trajets</Text><Text style={styles.subtitle}>Suivi et historique de vos courses</Text></View><TouchableOpacity accessibilityLabel="Actualiser" style={styles.refresh} onPress={()=>{setRefreshing(true);load();}}><Ionicons name="refresh" size={22} color={colors.primary}/></TouchableOpacity></View>{loading?<ActivityIndicator style={{marginTop:60}} color={colors.primary}/>:<ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load();}}/>}>{active?<><Text style={styles.section}>COURSE ACTIVE</Text>{card(active,true)}</>:null}<Text style={styles.section}>HISTORIQUE</Text>{history.length?history.map(r=>card(r)):<View style={styles.empty}><Ionicons name="map-outline" size={48} color={colors.textLight}/><Text style={styles.emptyTitle}>Aucun trajet terminé</Text><Text style={styles.subtitle}>Vos prochaines courses apparaîtront ici.</Text></View>}</ScrollView>}</SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:20},title:{fontSize:25,fontWeight:'800',color:colors.text},subtitle:{color:colors.textSecondary,marginTop:3},refresh:{width:44,height:44,borderRadius:14,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},content:{padding:18,paddingBottom:100},section:{fontSize:12,fontWeight:'800',letterSpacing:1.1,color:colors.textSecondary,marginTop:10,marginBottom:10},card:{flexDirection:'row',alignItems:'center',gap:12,padding:14,marginBottom:10,borderRadius:17,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border},active:{borderColor:colors.primary,borderWidth:2},icon:{width:46,height:46,borderRadius:14,alignItems:'center',justifyContent:'center'},grow:{flex:1},titleRow:{flexDirection:'row',alignItems:'center',gap:7},cardTitle:{fontSize:16,fontWeight:'700',color:colors.text},unread:{minWidth:20,height:20,borderRadius:10,backgroundColor:colors.danger,alignItems:'center',justifyContent:'center',paddingHorizontal:5},unreadText:{fontSize:10,fontWeight:'800',color:colors.white},meta:{fontSize:12,color:colors.textSecondary,marginTop:4},price:{fontSize:14,fontWeight:'800',color:colors.text,textAlign:'right'},chevron:{alignSelf:'flex-end',marginTop:4},empty:{alignItems:'center',paddingVertical:65},emptyTitle:{fontSize:18,fontWeight:'800',color:colors.text,marginTop:14}});
