import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import * as Location from 'expo-location';
import MapView,{UrlTile} from '../components/PlatformMap';
import {BackButton} from '../components/BackButton';
import {api} from '../api/config';
import {supabase} from '../api/supabase';
import {hydrateSession} from '../services/session';
import {colors} from '../theme/colors';

export default function ZemDriverScreen({navigation}:any){
  const [location,setLocation]=useState<Location.LocationObject|null>(null);
  const [online,setOnline]=useState(false);const onlineRef=useRef(false);
  const [offer,setOffer]=useState<any>();const [ride,setRide]=useState<any>();const [loading,setLoading]=useState(true);
  const loadOffer=async()=>{try{const s=await hydrateSession();if(!s)return;const r=await api('/zem/offers/current','GET',undefined,s.token);setOffer(r.offers?.[0]);}catch{}};
  const publish=async(loc:Location.LocationObject,isOnline=onlineRef.current)=>{try{await api('/zem/location','POST',{lat:loc.coords.latitude,lng:loc.coords.longitude,isOnline});}catch{}};
  useEffect(()=>{let watcher:Location.LocationSubscription|undefined;let timer:ReturnType<typeof setInterval>;let channel:any;(async()=>{const s=await hydrateSession();if(!s)return;const history=await api('/zem/history?page=1&page_size=20','GET',undefined,s.token).catch(()=>({rides:[]}));setRide(history.rides?.find((item:any)=>['accepted','driver_en_route','driver_arrived','ready_to_start','in_progress','driver_completed'].includes(item.status)));const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert('Localisation requise','Activez la localisation pour recevoir des courses.');setLoading(false);return;}const first=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setLocation(first);await publish(first,false);watcher=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,distanceInterval:25,timeInterval:8000},loc=>{setLocation(loc);publish(loc);});await loadOffer();timer=setInterval(loadOffer,7000);if(supabase){channel=supabase.channel(`zem-live-${s.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'ride_offers',filter:`zem_id=eq.${s.user.id}`},loadOffer).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rides',filter:`zem_id=eq.${s.user.id}`},({new:item})=>setRide(['completed','canceled','expired','no_show','disputed'].includes(item.status)?undefined:item)).subscribe();}setLoading(false);})();return()=>{watcher?.remove();if(timer)clearInterval(timer);if(channel&&supabase)supabase.removeChannel(channel);};},[]);
  const toggle=async()=>{if(!location)return;const next=!online;onlineRef.current=next;setOnline(next);await publish(location,next);if(next)loadOffer();};
  const respond=async(accept:boolean)=>{if(!offer)return;try{const result=await api(`/zem/offers/${offer.id}/respond`,'POST',{accept});setOffer(undefined);if(accept){setRide(result.ride);onlineRef.current=false;setOnline(false);if(location)await publish(location,false);navigation.navigate('RideDetail',{rideId:result.ride.id});}else await loadOffer();}catch(e:any){Alert.alert('Offre indisponible',e.message);await loadOffer();}};
  if(loading||!location)return <View style={styles.center}><ActivityIndicator color={colors.primary}/><Text style={styles.muted}>Acquisition de votre position…</Text></View>;
  return <View style={styles.container}><SafeAreaView style={styles.header}><BackButton color={colors.text}/><Text style={styles.title}>Espace conducteur</Text></SafeAreaView><MapView style={styles.map} initialRegion={{latitude:location.coords.latitude,longitude:location.coords.longitude,latitudeDelta:.04,longitudeDelta:.04}} showsUserLocation><UrlTile urlTemplate="https://tile.openstreetmap.org/{z}/{x}/{y}.png" maximumZ={19} flipY={false} tileSize={256} zIndex={1} shouldReplaceMapContent={true}/></MapView><View style={styles.panel}>{offer?<><View style={styles.row}><Ionicons name="navigate-circle-outline" size={26} color={colors.primary}/><Text style={styles.offerTitle}>Nouvelle proposition</Text></View><Text style={styles.offerMeta}>{offer.distance_km} km · {offer.price_fcfa} FCFA</Text><Text style={styles.muted}>Cette offre expire automatiquement. Acceptez-la uniquement si vous pouvez rejoindre le client.</Text><View style={styles.actions}><TouchableOpacity style={[styles.button,styles.flex,{backgroundColor:colors.danger}]} onPress={()=>respond(false)}><Text style={styles.buttonText}>Refuser</Text></TouchableOpacity><TouchableOpacity style={[styles.button,styles.flex,{backgroundColor:colors.success}]} onPress={()=>respond(true)}><Text style={styles.buttonText}>Accepter</Text></TouchableOpacity></View></>:ride?<><Text style={styles.offerTitle}>Course active</Text><TouchableOpacity style={[styles.button,{backgroundColor:colors.primary}]} onPress={()=>navigation.navigate('RideDetail',{rideId:ride.id})}><Text style={styles.buttonText}>Ouvrir le suivi et les actions</Text></TouchableOpacity></>:<><View style={styles.row}><View style={[styles.dot,{backgroundColor:online?colors.success:colors.textLight}]}/><Text style={styles.offerTitle}>{online?'Disponible pour les courses':'Indisponible'}</Text></View><TouchableOpacity style={[styles.button,{backgroundColor:online?colors.text:colors.success}]} onPress={toggle}><Text style={styles.buttonText}>{online?'Passer hors ligne':'Passer en ligne'}</Text></TouchableOpacity></>}</View></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{position:'absolute',zIndex:3,top:0,left:0,right:0,flexDirection:'row',alignItems:'center',gap:12,padding:15,backgroundColor:'rgba(255,255,255,.95)'},title:{fontSize:18,fontWeight:'800',color:colors.text},map:{flex:1},panel:{position:'absolute',left:12,right:12,bottom:18,padding:18,borderRadius:20,backgroundColor:colors.white,elevation:7,shadowColor:'#000',shadowOpacity:.12,shadowRadius:12},row:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginBottom:8},dot:{width:11,height:11,borderRadius:6},offerTitle:{fontWeight:'800',fontSize:18,color:colors.text,textAlign:'center'},offerMeta:{fontWeight:'800',fontSize:17,color:colors.primary,textAlign:'center',marginBottom:7},muted:{color:colors.textSecondary,textAlign:'center',marginTop:8},actions:{flexDirection:'row',gap:10,marginTop:15},button:{minHeight:50,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:14,paddingHorizontal:14},flex:{flex:1,marginTop:0},buttonText:{color:colors.white,fontWeight:'800'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10}});
